// ReSharper disable InconsistentNaming

namespace FoliCon.Properties.Langs;

public class LangProvider : INotifyPropertyChanged
{
    private static string _cultureInfoStr;
    internal static LangProvider Instance => ResourceHelper.GetResource<LangProvider>("FoliConLangs");
    public static string GetLang(string key) => Lang.ResourceManager.GetString(key, Culture);

    public static void SetLang(DependencyObject dependencyObject, DependencyProperty dependencyProperty, string key)
    {
        BindingOperations.SetBinding(dependencyObject, dependencyProperty, new Binding(key)
        {
            Source = Instance,
            Mode = BindingMode.OneWay
        });
    }

    public static CultureInfo Culture
    {
        get => Lang.Culture;
        set
        {
            if (value == null) return;
            if (Equals(_cultureInfoStr, value.EnglishName)) return;
            Lang.Culture = value;
            _cultureInfoStr = value.EnglishName;

            Instance.UpdateLangs();
        }
    }

    private void UpdateLangs()
    {
        OnPropertyChanged(nameof(APIKeysConfiguration));
        OnPropertyChanged(nameof(APIKeysNotProvided));
        OnPropertyChanged(nameof(About));
        OnPropertyChanged(nameof(Action));
        OnPropertyChanged(nameof(AddToContextMenu));
        OnPropertyChanged(nameof(All));
        OnPropertyChanged(nameof(AlwaysShowPosterWindow));
        OnPropertyChanged(nameof(AmbiguousTitleTooltip));
        OnPropertyChanged(nameof(AppWillClose));
        OnPropertyChanged(nameof(Apply));
        OnPropertyChanged(nameof(Arabic));
        OnPropertyChanged(nameof(Auto));
        OnPropertyChanged(nameof(BestSuitedForHorizontal));
        OnPropertyChanged(nameof(BrowseFolderDropHere));
        OnPropertyChanged(nameof(BrowseIconsDropHere));
        OnPropertyChanged(nameof(Cancel));
        OnPropertyChanged(nameof(ChangeLanguage));
        OnPropertyChanged(nameof(ChangePosterOverlay));
        OnPropertyChanged(nameof(CheckForUpdate));
        OnPropertyChanged(nameof(ChooseAnImage));
        OnPropertyChanged(nameof(ChoosePoster));
        OnPropertyChanged(nameof(ClientID));
        OnPropertyChanged(nameof(ClientSecret));
        OnPropertyChanged(nameof(Close));
        OnPropertyChanged(nameof(ClosingApplication));
        OnPropertyChanged(nameof(Configuration));
        OnPropertyChanged(nameof(Confirm));
        OnPropertyChanged(nameof(ConfirmExplorerRestart));
        OnPropertyChanged(nameof(ConfirmIconDeletion));
        OnPropertyChanged(nameof(ConfirmMediaInfoDeletion));
        OnPropertyChanged(nameof(ConfirmToOpenFolder));
        OnPropertyChanged(nameof(CreatingIcons));
        OnPropertyChanged(nameof(CustomIconSetter));
        OnPropertyChanged(nameof(CustomRating));
        OnPropertyChanged(nameof(CustomRatingTooltip));
        OnPropertyChanged(nameof(DeleteIcons));
        OnPropertyChanged(nameof(DeleteIconsConfirmation));
        OnPropertyChanged(nameof(DeleteIconsTooltip));
        OnPropertyChanged(nameof(DeleteMediaInfo));
        OnPropertyChanged(nameof(DeleteMediaInfoConfirmation));
        OnPropertyChanged(nameof(DeleteMediaInfoTooltip));
        OnPropertyChanged(nameof(DevelopedByDinesh));
        OnPropertyChanged(nameof(DirectoryIsEmpty));
        OnPropertyChanged(nameof(DownloadIt));
        OnPropertyChanged(nameof(Downloading));
        OnPropertyChanged(nameof(DownloadingIconWithCount));
        OnPropertyChanged(nameof(DownloadingIcons));
        OnPropertyChanged(nameof(EmptyDirectory));
        OnPropertyChanged(nameof(EnableErrorReporting));
        OnPropertyChanged(nameof(EnableErrorReportingTip));
        OnPropertyChanged(nameof(EnableSubfolderProcessing));
        OnPropertyChanged(nameof(Enabled));
        OnPropertyChanged(nameof(English));
        OnPropertyChanged(nameof(EnterTitlePlaceholder));
        OnPropertyChanged(nameof(EnterValidRegexPlaceholder));
        OnPropertyChanged(nameof(ExplorerIntegration));
        OnPropertyChanged(nameof(ExtractManually));
        OnPropertyChanged(nameof(Extracting));
        OnPropertyChanged(nameof(FailedFileAccessAt));
        OnPropertyChanged(nameof(FailedToSaveMediaInfoAt));
        OnPropertyChanged(nameof(FileIsInUse));
        OnPropertyChanged(nameof(Folder));
        OnPropertyChanged(nameof(FolderDoesNotExist));
        OnPropertyChanged(nameof(FolderError));
        OnPropertyChanged(nameof(Folders));
        OnPropertyChanged(nameof(FoldersProcessed));
        OnPropertyChanged(nameof(FoliConDescription));
        OnPropertyChanged(nameof(Game));
        OnPropertyChanged(nameof(HaveIcons));
        OnPropertyChanged(nameof(HaveIconsTooltip));
        OnPropertyChanged(nameof(Help));
        OnPropertyChanged(nameof(HelpDocument));
        OnPropertyChanged(nameof(Hindi));
        OnPropertyChanged(nameof(IconCreated));
        OnPropertyChanged(nameof(IconCreatedWithCount));
        OnPropertyChanged(nameof(IconMode));
        OnPropertyChanged(nameof(IconReloadMayTakeTime));
        OnPropertyChanged(nameof(Icons));
        OnPropertyChanged(nameof(IconsAlready));
        OnPropertyChanged(nameof(IconsCreated));
        OnPropertyChanged(nameof(Idle));
        OnPropertyChanged(nameof(Ignore));
        OnPropertyChanged(nameof(IgnoreAmbiguousTitle));
        OnPropertyChanged(nameof(InvalidPath));
        OnPropertyChanged(nameof(InvalidRegex));
        OnPropertyChanged(nameof(InvalidRegexMessage));
        OnPropertyChanged(nameof(License));
        OnPropertyChanged(nameof(LicenseInfo));
        OnPropertyChanged(nameof(Load));
        OnPropertyChanged(nameof(LoadingPosters));
        OnPropertyChanged(nameof(MakeIcons));
        OnPropertyChanged(nameof(ManualExplorer));
        OnPropertyChanged(nameof(MediaRating));
        OnPropertyChanged(nameof(MediaTitle));
        OnPropertyChanged(nameof(Movie));
        OnPropertyChanged(nameof(NetworkError));
        OnPropertyChanged(nameof(NetworkNotAvailable));
        OnPropertyChanged(nameof(NewVersionFound));
        OnPropertyChanged(nameof(NoFolderOrIconAlready));
        OnPropertyChanged(nameof(NoFoldersToProcess));
        OnPropertyChanged(nameof(NoIconsSelected));
        OnPropertyChanged(nameof(NoIconsToApply));
        OnPropertyChanged(nameof(NoInternet));
        OnPropertyChanged(nameof(NoPosterFound));
        OnPropertyChanged(nameof(NoResult));
        OnPropertyChanged(nameof(NoResultFound));
        OnPropertyChanged(nameof(NoResultFoundTryCorrectTitle));
        OnPropertyChanged(nameof(NothingFoundFor));
        OnPropertyChanged(nameof(OK));
        OnPropertyChanged(nameof(OnlyKeepExactMatches));
        OnPropertyChanged(nameof(Or));
        OnPropertyChanged(nameof(OutOf));
        OnPropertyChanged(nameof(Overlay));
        OnPropertyChanged(nameof(Pattern));
        OnPropertyChanged(nameof(Patterns));
        OnPropertyChanged(nameof(PickIconWithName));
        OnPropertyChanged(nameof(PickSelected));
        OnPropertyChanged(nameof(Poster));
        OnPropertyChanged(nameof(PosterIconOverlay));
        OnPropertyChanged(nameof(PosterOverlayTooltip));
        OnPropertyChanged(nameof(Previewer));
        OnPropertyChanged(nameof(Professional));
        OnPropertyChanged(nameof(Rating));
        OnPropertyChanged(nameof(RemoveFromContextMenu));
        OnPropertyChanged(nameof(ResetDefaultPoster));
        OnPropertyChanged(nameof(RestartAsAdmin));
        OnPropertyChanged(nameof(RestartExplorer));
        OnPropertyChanged(nameof(RestartExplorerConfirmation));
        OnPropertyChanged(nameof(RestartExplorerTooltip));
        OnPropertyChanged(nameof(Russian));
        OnPropertyChanged(nameof(Save));
        OnPropertyChanged(nameof(SearchMode));
        OnPropertyChanged(nameof(SearchResult));
        OnPropertyChanged(nameof(Searching));
        OnPropertyChanged(nameof(SearchingWithCount));
        OnPropertyChanged(nameof(SearchingWithName));
        OnPropertyChanged(nameof(SeeMorePosters));
        OnPropertyChanged(nameof(SelectFolder));
        OnPropertyChanged(nameof(SelectIconsDirectory));
        OnPropertyChanged(nameof(SelectPosterIconOverlay));
        OnPropertyChanged(nameof(Settings));
        OnPropertyChanged(nameof(ShowMore));
        OnPropertyChanged(nameof(ShowPosterWindowTooltip));
        OnPropertyChanged(nameof(ShowRatingBadge));
        OnPropertyChanged(nameof(ShowRatingBadgeTooltip));
        OnPropertyChanged(nameof(Skip));
        OnPropertyChanged(nameof(SkipThisPlaceholder));
        OnPropertyChanged(nameof(SkipThisTitle));
        OnPropertyChanged(nameof(Spanish));
        OnPropertyChanged(nameof(StopSearching));
        OnPropertyChanged(nameof(SubfolderProcessing));
        OnPropertyChanged(nameof(TMDBAPIKey));
        OnPropertyChanged(nameof(TV));
        OnPropertyChanged(nameof(Test));
        OnPropertyChanged(nameof(Theme));
        OnPropertyChanged(nameof(ThemeDark));
        OnPropertyChanged(nameof(ThemeLight));
        OnPropertyChanged(nameof(ThemeSystem));
        OnPropertyChanged(nameof(ThisIsLatestVersion));
        OnPropertyChanged(nameof(Title));
        OnPropertyChanged(nameof(ToForceReload));
        OnPropertyChanged(nameof(UnauthorizedAccess));
        OnPropertyChanged(nameof(Undo));
        OnPropertyChanged(nameof(UndoSuccessful));
        OnPropertyChanged(nameof(UpdateNow));
        OnPropertyChanged(nameof(UsePosterOverlay));
        OnPropertyChanged(nameof(Version));
        OnPropertyChanged(nameof(VideoUnavailable));
        OnPropertyChanged(nameof(WebView2DownloadConfirmation));
        OnPropertyChanged(nameof(WebView2DownloadConfirmationHeader));
        OnPropertyChanged(nameof(WritePermissionAllowed));
        OnPropertyChanged(nameof(WritePermissionNotAllowed));
        OnPropertyChanged(nameof(Year));
    }

    public string APIKeysConfiguration => Lang.APIKeysConfiguration;
    public string APIKeysNotProvided => Lang.APIKeysNotProvided;
    public string About => Lang.About;
    public string Action => Lang.Action;
    public string AddToContextMenu => Lang.AddToContextMenu;
    public string All => Lang.All;
    public string AlwaysShowPosterWindow => Lang.AlwaysShowPosterWindow;
    public string AmbiguousTitleTooltip => Lang.AmbiguousTitleTooltip;
    public string AppWillClose => Lang.AppWillClose;
    public string Apply => Lang.Apply;
    public string Arabic => Lang.Arabic;
    public string Auto => Lang.Auto;
    public string BestSuitedForHorizontal => Lang.BestSuitedForHorizontal;
    public string BrowseFolderDropHere => Lang.BrowseFolderDropHere;
    public string BrowseIconsDropHere => Lang.BrowseIconsDropHere;
    public string Cancel => Lang.Cancel;
    public string ChangeLanguage => Lang.ChangeLanguage;
    public string ChangePosterOverlay => Lang.ChangePosterOverlay;
    public string CheckForUpdate => Lang.CheckForUpdate;
    public string ChooseAnImage => Lang.ChooseAnImage;
    public string ChoosePoster => Lang.ChoosePoster;
    public string ClientID => Lang.ClientID;
    public string ClientSecret => Lang.ClientSecret;
    public string Close => Lang.Close;
    public string ClosingApplication => Lang.ClosingApplication;
    public string Configuration => Lang.Configuration;
    public string Confirm => Lang.Confirm;
    public string ConfirmExplorerRestart => Lang.ConfirmExplorerRestart;
    public string ConfirmIconDeletion => Lang.ConfirmIconDeletion;
    public string ConfirmMediaInfoDeletion => Lang.ConfirmMediaInfoDeletion;
    public string ConfirmToOpenFolder => Lang.ConfirmToOpenFolder;
    public string CreatingIcons => Lang.CreatingIcons;
    public string CustomIconSetter => Lang.CustomIconSetter;
    public string CustomRating => Lang.CustomRating;
    public string CustomRatingTooltip => Lang.CustomRatingTooltip;
    public string DeleteIcons => Lang.DeleteIcons;
    public string DeleteIconsConfirmation => Lang.DeleteIconsConfirmation;
    public string DeleteIconsTooltip => Lang.DeleteIconsTooltip;
    public string DeleteMediaInfo => Lang.DeleteMediaInfo;
    public string DeleteMediaInfoConfirmation => Lang.DeleteMediaInfoConfirmation;
    public string DeleteMediaInfoTooltip => Lang.DeleteMediaInfoTooltip;
    public string DevelopedByDinesh => Lang.DevelopedByDinesh;
    public string DirectoryIsEmpty => Lang.DirectoryIsEmpty;
    public string DownloadIt => Lang.DownloadIt;
    public string Downloading => Lang.Downloading;
    public string DownloadingIconWithCount => Lang.DownloadingIconWithCount;
    public string DownloadingIcons => Lang.DownloadingIcons;
    public string EmptyDirectory => Lang.EmptyDirectory;
    public string EnableErrorReporting => Lang.EnableErrorReporting;
    public string EnableErrorReportingTip => Lang.EnableErrorReportingTip;
    public string EnableSubfolderProcessing => Lang.EnableSubfolderProcessing;
    public string Enabled => Lang.Enabled;
    public string English => Lang.English;
    public string EnterTitlePlaceholder => Lang.EnterTitlePlaceholder;
    public string EnterValidRegexPlaceholder => Lang.EnterValidRegexPlaceholder;
    public string ExceptionOccurred => Lang.ExceptionOccurred;
    public string ExplorerIntegration => Lang.ExplorerIntegration;
    public string ExtractManually => Lang.ExtractManually;
    public string Extracting => Lang.Extracting;
    public string FailedFileAccessAt => Lang.FailedFileAccessAt;
    public string FailedToSaveMediaInfoAt => Lang.FailedToSaveMediaInfoAt;
    public string FileIsInUse => Lang.FileIsInUse;
    public string Folder => Lang.Folder;
    public string FolderDoesNotExist => Lang.FolderDoesNotExist;
    public string FolderError => Lang.FolderError;
    public string Folders => Lang.Folders;
    public string FoldersProcessed => Lang.FoldersProcessed;
    public string FoliConDescription => Lang.FoliConDescription;
    public string Game => Lang.Game;
    public string HaveIcons => Lang.HaveIcons;
    public string HaveIconsTooltip => Lang.HaveIconsTooltip;
    public string Help => Lang.Help;
    public string HelpDocument => Lang.HelpDocument;
    public string Hindi => Lang.Hindi;
    public string IconCreated => Lang.IconCreated;
    public string IconCreatedWithCount => Lang.IconCreatedWithCount;
    public string IconMode => Lang.IconMode;
    public string IconReloadMayTakeTime => Lang.IconReloadMayTakeTime;
    public string Icons => Lang.Icons;
    public string IconsAlready => Lang.IconsAlready;
    public string IconsCreated => Lang.IconsCreated;
    public string Idle => Lang.Idle;
    public string Ignore => Lang.Ignore;
    public string IgnoreAmbiguousTitle => Lang.IgnoreAmbiguousTitle;
    public string InvalidPath => Lang.InvalidPath;
    public string InvalidRegex => Lang.InvalidRegex;
    public string InvalidRegexMessage => Lang.InvalidRegexMessage;
    public string License => Lang.License;
    public string LicenseInfo => Lang.LicenseInfo;
    public string Load => Lang.Load;
    public string LoadingPosters => Lang.LoadingPosters;
    public string MakeIcons => Lang.MakeIcons;
    public string ManualExplorer => Lang.ManualExplorer;
    public string MediaRating => Lang.MediaRating;
    public string MediaTitle => Lang.MediaTitle;
    public string Movie => Lang.Movie;
    public string NetworkError => Lang.NetworkError;
    public string NetworkNotAvailable => Lang.NetworkNotAvailable;
    public string NewVersionFound => Lang.NewVersionFound;
    public string NoFolderOrIconAlready => Lang.NoFolderOrIconAlready;
    public string NoFoldersToProcess => Lang.NoFoldersToProcess;
    public string NoIconsSelected => Lang.NoIconsSelected;
    public string NoIconsToApply => Lang.NoIconsToApply;
    public string NoInternet => Lang.NoInternet;
    public string NoPosterFound => Lang.NoPosterFound;
    public string NoResult => Lang.NoResult;
    public string NoResultFound => Lang.NoResultFound;
    public string NoResultFoundTryCorrectTitle => Lang.NoResultFoundTryCorrectTitle;
    public string NothingFoundFor => Lang.NothingFoundFor;
    public string OK => Lang.OK;
    public string OnlyKeepExactMatches => Lang.OnlyKeepExactMatches;
    public string Or => Lang.Or;
    public string OutOf => Lang.OutOf;
    public string Overlay => Lang.Overlay;
    public string Pattern => Lang.Pattern;
    public string Patterns => Lang.Patterns;
    public string PickIconWithName => Lang.PickIconWithName;
    public string PickSelected => Lang.PickSelected;
    public string Poster => Lang.Poster;
    public string PosterIconOverlay => Lang.PosterIconOverlay;
    public string PosterOverlayTooltip => Lang.PosterOverlayTooltip;
    public string Previewer => Lang.Previewer;
    public string Professional => Lang.Professional;
    public string Rating => Lang.Rating;
    public string RemoveFromContextMenu => Lang.RemoveFromContextMenu;
    public string ResetDefaultPoster => Lang.ResetDefaultPoster;
    public string RestartAsAdmin => Lang.RestartAsAdmin;
    public string RestartExplorer => Lang.RestartExplorer;
    public string RestartExplorerConfirmation => Lang.RestartExplorerConfirmation;
    public string RestartExplorerTooltip => Lang.RestartExplorerTooltip;
    public string Russian => Lang.Russian;
    public string Save => Lang.Save;
    public string SearchMode => Lang.SearchMode;
    public string SearchResult => Lang.SearchResult;
    public string Searching => Lang.Searching;
    public string SearchingWithCount => Lang.SearchingWithCount;
    public string SearchingWithName => Lang.SearchingWithName;
    public string SeeMorePosters => Lang.SeeMorePosters;
    public string SelectFolder => Lang.SelectFolder;
    public string SelectIconsDirectory => Lang.SelectIconsDirectory;
    public string SelectPosterIconOverlay => Lang.SelectPosterIconOverlay;
    public string Settings => Lang.Settings;
    public string ShowMore => Lang.ShowMore;
    public string ShowPosterWindowTooltip => Lang.ShowPosterWindowTooltip;
    public string ShowRatingBadge => Lang.ShowRatingBadge;
    public string ShowRatingBadgeTooltip => Lang.ShowRatingBadgeTooltip;
    public string Skip => Lang.Skip;
    public string SkipThisPlaceholder => Lang.SkipThisPlaceholder;
    public string SkipThisTitle => Lang.SkipThisTitle;
    public string Spanish => Lang.Spanish;
    public string StopSearching => Lang.StopSearching;
    public string SubfolderProcessing => Lang.SubfolderProcessing;
    public string TMDBAPIKey => Lang.TMDBAPIKey;
    public string TV => Lang.TV;
    public string Test => Lang.Test;
    public string Theme => Lang.Theme;
    public string ThemeDark => Lang.ThemeDark;
    public string ThemeLight => Lang.ThemeLight;
    public string ThemeSystem => Lang.ThemeSystem;
    public string ThisIsLatestVersion => Lang.ThisIsLatestVersion;
    public string Title => Lang.Title;
    public string ToForceReload => Lang.ToForceReload;
    public string UnauthorizedAccess => Lang.UnauthorizedAccess;
    public string Undo => Lang.Undo;
    public string UndoSuccessful => Lang.UndoSuccessful;
    public string UpdateNow => Lang.UpdateNow;
    public string UsePosterOverlay => Lang.UsePosterOverlay;
    public string Version => Lang.Version;
    public string VideoUnavailable => Lang.VideoUnavailable;
    public string WebView2DownloadConfirmation => Lang.WebView2DownloadConfirmation;
    public string WebView2DownloadConfirmationHeader => Lang.WebView2DownloadConfirmationHeader;
    public string WritePermissionAllowed => Lang.WritePermissionAllowed;
    public string WritePermissionNotAllowed => Lang.WritePermissionNotAllowed;
    public string Year => Lang.Year;


    public event PropertyChangedEventHandler PropertyChanged;

    protected virtual void OnPropertyChanged(string propertyName) =>
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
}

public class LangKeys
{
    public static string APIKeysConfiguration = nameof(APIKeysConfiguration);
    public static string APIKeysNotProvided = nameof(APIKeysNotProvided);
    public static string About = nameof(About);
    public static string Action = nameof(Action);
    public static string AddToContextMenu = nameof(AddToContextMenu);
    public static string All = nameof(All);
    public static string AlwaysShowPosterWindow = nameof(AlwaysShowPosterWindow);
    public static string AmbiguousTitleTooltip = nameof(AmbiguousTitleTooltip);
    public static string AppWillClose = nameof(AppWillClose);
    public static string Apply = nameof(Apply);
    public static string Arabic = nameof(Arabic);
    public static string Auto = nameof(Auto);
    public static string BestSuitedForHorizontal = nameof(BestSuitedForHorizontal);
    public static string BrowseFolderDropHere = nameof(BrowseFolderDropHere);
    public static string BrowseIconsDropHere = nameof(BrowseIconsDropHere);
    public static string Cancel = nameof(Cancel);
    public static string ChangeLanguage = nameof(ChangeLanguage);
    public static string ChangePosterOverlay = nameof(ChangePosterOverlay);
    public static string CheckForUpdate = nameof(CheckForUpdate);
    public static string ChooseAnImage = nameof(ChooseAnImage);
    public static string ChoosePoster = nameof(ChoosePoster);
    public static string ClientID = nameof(ClientID);
    public static string ClientSecret = nameof(ClientSecret);
    public static string Close = nameof(Close);
    public static string ClosingApplication = nameof(ClosingApplication);
    public static string Configuration = nameof(Configuration);
    public static string Confirm = nameof(Confirm);
    public static string ConfirmExplorerRestart = nameof(ConfirmExplorerRestart);
    public static string ConfirmIconDeletion = nameof(ConfirmIconDeletion);
    public static string ConfirmMediaInfoDeletion = nameof(ConfirmMediaInfoDeletion);
    public static string ConfirmToOpenFolder = nameof(ConfirmToOpenFolder);
    public static string CreatingIcons = nameof(CreatingIcons);
    public static string CustomIconSetter = nameof(CustomIconSetter);
    public static string CustomRating = nameof(CustomRating);
    public static string CustomRatingTooltip = nameof(CustomRatingTooltip);
    public static string DeleteIcons = nameof(DeleteIcons);
    public static string DeleteIconsConfirmation = nameof(DeleteIconsConfirmation);
    public static string DeleteIconsTooltip = nameof(DeleteIconsTooltip);
    public static string DeleteMediaInfo = nameof(DeleteMediaInfo);
    public static string DeleteMediaInfoConfirmation = nameof(DeleteMediaInfoConfirmation);
    public static string DeleteMediaInfoTooltip = nameof(DeleteMediaInfoTooltip);
    public static string DevelopedByDinesh = nameof(DevelopedByDinesh);
    public static string DirectoryIsEmpty = nameof(DirectoryIsEmpty);
    public static string DownloadIt = nameof(DownloadIt);
    public static string Downloading = nameof(Downloading);
    public static string DownloadingIconWithCount = nameof(DownloadingIconWithCount);
    public static string DownloadingIcons = nameof(DownloadingIcons);
    public static string EmptyDirectory = nameof(EmptyDirectory);
    public static string EnableErrorReporting = nameof(EnableErrorReporting);
    public static string EnableErrorReportingTip = nameof(EnableErrorReportingTip);
    public static string EnableSubfolderProcessing = nameof(EnableSubfolderProcessing);
    public static string Enabled = nameof(Enabled);
    public static string English = nameof(English);
    public static string EnterTitlePlaceholder = nameof(EnterTitlePlaceholder);
    public static string EnterValidRegexPlaceholder = nameof(EnterValidRegexPlaceholder);
    public static string ExceptionOccurred = nameof(ExceptionOccurred);
    public static string ExplorerIntegration = nameof(ExplorerIntegration);
    public static string ExtractManually = nameof(ExtractManually);
    public static string Extracting = nameof(Extracting);
    public static string FailedFileAccessAt = nameof(FailedFileAccessAt);
    public static string FailedToSaveMediaInfoAt = nameof(FailedToSaveMediaInfoAt);
    public static string FileIsInUse = nameof(FileIsInUse);
    public static string Folder = nameof(Folder);
    public static string FolderDoesNotExist = nameof(FolderDoesNotExist);
    public static string FolderError = nameof(FolderError);
    public static string Folders = nameof(Folders);
    public static string FoldersProcessed = nameof(FoldersProcessed);
    public static string FoliConDescription = nameof(FoliConDescription);
    public static string Game = nameof(Game);
    public static string HaveIcons = nameof(HaveIcons);
    public static string HaveIconsTooltip = nameof(HaveIconsTooltip);
    public static string Help = nameof(Help);
    public static string HelpDocument = nameof(HelpDocument);
    public static string Hindi = nameof(Hindi);
    public static string IconCreated = nameof(IconCreated);
    public static string IconCreatedWithCount = nameof(IconCreatedWithCount);
    public static string IconMode = nameof(IconMode);
    public static string IconReloadMayTakeTime = nameof(IconReloadMayTakeTime);
    public static string Icons = nameof(Icons);
    public static string IconsAlready = nameof(IconsAlready);
    public static string IconsCreated = nameof(IconsCreated);
    public static string Idle = nameof(Idle);
    public static string Ignore = nameof(Ignore);
    public static string IgnoreAmbiguousTitle = nameof(IgnoreAmbiguousTitle);
    public static string InvalidPath = nameof(InvalidPath);
    public static string InvalidRegex = nameof(InvalidRegex);
    public static string InvalidRegexMessage = nameof(InvalidRegexMessage);
    public static string License = nameof(License);
    public static string LicenseInfo = nameof(LicenseInfo);
    public static string Load = nameof(Load);
    public static string LoadingPosters = nameof(LoadingPosters);
    public static string MakeIcons = nameof(MakeIcons);
    public static string ManualExplorer = nameof(ManualExplorer);
    public static string MediaRating = nameof(MediaRating);
    public static string MediaTitle = nameof(MediaTitle);
    public static string Movie = nameof(Movie);
    public static string NetworkError = nameof(NetworkError);
    public static string NetworkNotAvailable = nameof(NetworkNotAvailable);
    public static string NewVersionFound = nameof(NewVersionFound);
    public static string NoFolderOrIconAlready = nameof(NoFolderOrIconAlready);
    public static string NoFoldersToProcess = nameof(NoFoldersToProcess);
    public static string NoIconsSelected = nameof(NoIconsSelected);
    public static string NoIconsToApply = nameof(NoIconsToApply);
    public static string NoInternet = nameof(NoInternet);
    public static string NoPosterFound = nameof(NoPosterFound);
    public static string NoResult = nameof(NoResult);
    public static string NoResultFound = nameof(NoResultFound);
    public static string NoResultFoundTryCorrectTitle = nameof(NoResultFoundTryCorrectTitle);
    public static string NothingFoundFor = nameof(NothingFoundFor);
    public static string OK = nameof(OK);
    public static string OnlyKeepExactMatches = nameof(OnlyKeepExactMatches);
    public static string Or = nameof(Or);
    public static string OutOf = nameof(OutOf);
    public static string Overlay = nameof(Overlay);
    public static string Pattern = nameof(Pattern);
    public static string Patterns = nameof(Patterns);
    public static string PickIconWithName = nameof(PickIconWithName);
    public static string PickSelected = nameof(PickSelected);
    public static string Poster = nameof(Poster);
    public static string PosterIconOverlay = nameof(PosterIconOverlay);
    public static string PosterOverlayTooltip = nameof(PosterOverlayTooltip);
    public static string Previewer = nameof(Previewer);
    public static string Professional = nameof(Professional);
    public static string Rating = nameof(Rating);
    public static string RemoveFromContextMenu = nameof(RemoveFromContextMenu);
    public static string ResetDefaultPoster = nameof(ResetDefaultPoster);
    public static string RestartAsAdmin = nameof(RestartAsAdmin);
    public static string RestartExplorer = nameof(RestartExplorer);
    public static string RestartExplorerConfirmation = nameof(RestartExplorerConfirmation);
    public static string RestartExplorerTooltip = nameof(RestartExplorerTooltip);
    public static string Russian = nameof(Russian);
    public static string Save = nameof(Save);
    public static string SearchMode = nameof(SearchMode);
    public static string SearchResult = nameof(SearchResult);
    public static string Searching = nameof(Searching);
    public static string SearchingWithCount = nameof(SearchingWithCount);
    public static string SearchingWithName = nameof(SearchingWithName);
    public static string SeeMorePosters = nameof(SeeMorePosters);
    public static string SelectFolder = nameof(SelectFolder);
    public static string SelectIconsDirectory = nameof(SelectIconsDirectory);
    public static string SelectPosterIconOverlay = nameof(SelectPosterIconOverlay);
    public static string Settings = nameof(Settings);
    public static string ShowMore = nameof(ShowMore);
    public static string ShowPosterWindowTooltip = nameof(ShowPosterWindowTooltip);
    public static string ShowRatingBadge = nameof(ShowRatingBadge);
    public static string ShowRatingBadgeTooltip = nameof(ShowRatingBadgeTooltip);
    public static string Skip = nameof(Skip);
    public static string SkipThisPlaceholder = nameof(SkipThisPlaceholder);
    public static string SkipThisTitle = nameof(SkipThisTitle);
    public static string Spanish = nameof(Spanish);
    public static string StopSearching = nameof(StopSearching);
    public static string SubfolderProcessing = nameof(SubfolderProcessing);
    public static string TMDBAPIKey = nameof(TMDBAPIKey);
    public static string TV = nameof(TV);
    public static string Test = nameof(Test);
    public static string Theme = nameof(Theme);
    public static string ThemeDark = nameof(ThemeDark);
    public static string ThemeLight = nameof(ThemeLight);
    public static string ThemeSystem = nameof(ThemeSystem);
    public static string ThisIsLatestVersion = nameof(ThisIsLatestVersion);
    public static string Title = nameof(Title);
    public static string ToForceReload = nameof(ToForceReload);
    public static string UnauthorizedAccess = nameof(UnauthorizedAccess);
    public static string Undo = nameof(Undo);
    public static string UndoSuccessful = nameof(UndoSuccessful);
    public static string UpdateNow = nameof(UpdateNow);
    public static string UsePosterOverlay = nameof(UsePosterOverlay);
    public static string Version = nameof(Version);
    public static string VideoUnavailable = nameof(VideoUnavailable);
    public static string WebView2DownloadConfirmation = nameof(WebView2DownloadConfirmation);
    public static string WebView2DownloadConfirmationHeader = nameof(WebView2DownloadConfirmationHeader);
    public static string WritePermissionAllowed = nameof(WritePermissionAllowed);
    public static string WritePermissionNotAllowed = nameof(WritePermissionNotAllowed);
    public static string Year = nameof(Year);
    
}