// ReSharper disable InconsistentNaming

using System.Diagnostics.CodeAnalysis;

namespace FoliCon.Properties.Langs;

[SuppressMessage("Performance", "CA1822:Mark members as static",
    Justification = "XAML data binding requires instance properties.")]
[SuppressMessage("Sonar", "S2325:Methods and properties that don't access instance data should be static",
    Justification = "If we make properties static, it will break MVVM change pattern, XAML bindings like " +
                    "{Binding Source={StaticResource FoliConLangs}, Path=InvalidApiKey} would stop working because XAML " +
                    "data binding requires instance properties.")]
[Localizable(false)]
public class LangProvider : INotifyPropertyChanged
{
    protected LangProvider()
    {
    }

    private static string _cultureInfoStr;
    internal static LangProvider Instance => ResourceHelper.GetResource<LangProvider>("FoliConLangs");
    public static string GetLang(string key) => Lang.ResourceManager.GetString(key, Culture);

    public static void SetLang(DependencyObject dependencyObject, DependencyProperty dependencyProperty, string key)
    {
        BindingOperations.SetBinding(dependencyObject, dependencyProperty,
            new Binding(key) { Source = Instance, Mode = BindingMode.OneWay });
    }

    public static CultureInfo Culture
    {
        get => Lang.Culture;
        set
        {
            if (value == null)
            {
                return;
            }

            if (Equals(_cultureInfoStr, value.EnglishName))
            {
                return;
            }

            Lang.Culture = value;
            _cultureInfoStr = value.EnglishName;

            Instance.UpdateLangs();
        }
    }

    private void UpdateLangs()
    {
        OnPropertyChanged(nameof(APIKeysConfiguration));
        OnPropertyChanged(nameof(APIKeysNotProvided));
        OnPropertyChanged(nameof(About));
        OnPropertyChanged(nameof(Action));
        OnPropertyChanged(nameof(AddToContextMenu));
        OnPropertyChanged(nameof(All));
        OnPropertyChanged(nameof(AlwaysShowPosterWindow));
        OnPropertyChanged(nameof(AmbiguousTitleTooltip));
        OnPropertyChanged(nameof(AppWillClose));
        OnPropertyChanged(nameof(Apply));
        OnPropertyChanged(nameof(Arabic));
        OnPropertyChanged(nameof(Auto));
        OnPropertyChanged(nameof(BestSuitedForHorizontal));
        OnPropertyChanged(nameof(BrowseFolderDropHere));
        OnPropertyChanged(nameof(BrowseIconsDropHere));
        OnPropertyChanged(nameof(Cancel));
        OnPropertyChanged(nameof(ChangeLanguage));
        OnPropertyChanged(nameof(ChangePosterOverlay));
        OnPropertyChanged(nameof(CheckForUpdate));
        OnPropertyChanged(nameof(ChooseAnImage));
        OnPropertyChanged(nameof(ChoosePoster));
        OnPropertyChanged(nameof(ClientID));
        OnPropertyChanged(nameof(ClientSecret));
        OnPropertyChanged(nameof(Close));
        OnPropertyChanged(nameof(ClosingApplication));
        OnPropertyChanged(nameof(Configuration));
        OnPropertyChanged(nameof(Confirm));
        OnPropertyChanged(nameof(ConfirmExplorerRestart));
        OnPropertyChanged(nameof(ConfirmIconDeletion));
        OnPropertyChanged(nameof(ConfirmMediaInfoDeletion));
        OnPropertyChanged(nameof(ConfirmToOpenFolder));
        OnPropertyChanged(nameof(CreatingIconWithCount));
        OnPropertyChanged(nameof(CreatingIcons));
        OnPropertyChanged(nameof(CustomIconSetter));
        OnPropertyChanged(nameof(CustomRating));
        OnPropertyChanged(nameof(CustomRatingTooltip));
        OnPropertyChanged(nameof(DeleteIcons));
        OnPropertyChanged(nameof(DeleteIconsConfirmation));
        OnPropertyChanged(nameof(DeleteIconsTooltip));
        OnPropertyChanged(nameof(DeleteMediaInfo));
        OnPropertyChanged(nameof(DeleteMediaInfoConfirmation));
        OnPropertyChanged(nameof(DeleteMediaInfoTooltip));
        OnPropertyChanged(nameof(DevelopedByDinesh));
        OnPropertyChanged(nameof(DirectoryIsEmpty));
        OnPropertyChanged(nameof(DownloadIt));
        OnPropertyChanged(nameof(Downloading));
        OnPropertyChanged(nameof(DownloadingIconWithCount));
        OnPropertyChanged(nameof(DownloadingIcons));
        OnPropertyChanged(nameof(EmptyDirectory));
        OnPropertyChanged(nameof(EnableErrorReporting));
        OnPropertyChanged(nameof(EnableErrorReportingTip));
        OnPropertyChanged(nameof(EnableSubfolderProcessing));
        OnPropertyChanged(nameof(Enabled));
        OnPropertyChanged(nameof(English));
        OnPropertyChanged(nameof(EnterTitlePlaceholder));
        OnPropertyChanged(nameof(EnterValidRegexPlaceholder));
        OnPropertyChanged(nameof(ExplorerIntegration));
        OnPropertyChanged(nameof(ExtractGallery));
        OnPropertyChanged(nameof(Extracting));
        OnPropertyChanged(nameof(FailedFileAccessAt));
        OnPropertyChanged(nameof(FailedToSaveMediaInfoAt));
        OnPropertyChanged(nameof(FileIsInUse));
        OnPropertyChanged(nameof(Folder));
        OnPropertyChanged(nameof(FolderDoesNotExist));
        OnPropertyChanged(nameof(FolderError));
        OnPropertyChanged(nameof(Folders));
        OnPropertyChanged(nameof(FoldersProcessed));
        OnPropertyChanged(nameof(FoliConDescription));
        OnPropertyChanged(nameof(Game));
        OnPropertyChanged(nameof(HaveIcons));
        OnPropertyChanged(nameof(HaveIconsTooltip));
        OnPropertyChanged(nameof(Help));
        OnPropertyChanged(nameof(HelpDocument));
        OnPropertyChanged(nameof(Hindi));
        OnPropertyChanged(nameof(IconCreated));
        OnPropertyChanged(nameof(IconCreatedWithCount));
        OnPropertyChanged(nameof(IconMode));
        OnPropertyChanged(nameof(IconReloadMayTakeTime));
        OnPropertyChanged(nameof(Icons));
        OnPropertyChanged(nameof(IconsAlready));
        OnPropertyChanged(nameof(IconsCreated));
        OnPropertyChanged(nameof(Idle));
        OnPropertyChanged(nameof(Ignore));
        OnPropertyChanged(nameof(IgnoreAmbiguousTitle));
        OnPropertyChanged(nameof(IncludeAlreadyProcessed));
        OnPropertyChanged(nameof(IncludeAlreadyProcessedTooltip));
        OnPropertyChanged(nameof(InvalidPath));
        OnPropertyChanged(nameof(InvalidRegex));
        OnPropertyChanged(nameof(InvalidRegexMessage));
        OnPropertyChanged(nameof(License));
        OnPropertyChanged(nameof(LicenseInfo));
        OnPropertyChanged(nameof(Load));
        OnPropertyChanged(nameof(LoadingPosters));
        OnPropertyChanged(nameof(MakeIcons));
        OnPropertyChanged(nameof(MaxDepth));
        OnPropertyChanged(nameof(MaxDepthTooltip));
        OnPropertyChanged(nameof(ManualExplorer));
        OnPropertyChanged(nameof(MediaRating));
        OnPropertyChanged(nameof(MediaTitle));
        OnPropertyChanged(nameof(Movie));
        OnPropertyChanged(nameof(NetworkError));
        OnPropertyChanged(nameof(NetworkNotAvailable));
        OnPropertyChanged(nameof(NewVersionFound));
        OnPropertyChanged(nameof(NoFolderOrIconAlready));
        OnPropertyChanged(nameof(NoFoldersToProcess));
        OnPropertyChanged(nameof(NoIconsSelected));
        OnPropertyChanged(nameof(NoIconsToApply));
        OnPropertyChanged(nameof(NoInternet));
        OnPropertyChanged(nameof(NoPosterFound));
        OnPropertyChanged(nameof(NoResult));
        OnPropertyChanged(nameof(NoResultFound));
        OnPropertyChanged(nameof(NoResultFoundTryCorrectTitle));
        OnPropertyChanged(nameof(NothingFoundFor));
        OnPropertyChanged(nameof(OK));
        OnPropertyChanged(nameof(OnlyKeepExactMatches));
        OnPropertyChanged(nameof(Or));
        OnPropertyChanged(nameof(OutOf));
        OnPropertyChanged(nameof(Overlay));
        OnPropertyChanged(nameof(Pattern));
        OnPropertyChanged(nameof(Patterns));
        OnPropertyChanged(nameof(PickIconWithName));
        OnPropertyChanged(nameof(PickSelected));
        OnPropertyChanged(nameof(Poster));
        OnPropertyChanged(nameof(PosterIconOverlay));
        OnPropertyChanged(nameof(PosterOverlayTooltip));
        OnPropertyChanged(nameof(Previewer));
        OnPropertyChanged(nameof(ProcessSelectedFolder));
        OnPropertyChanged(nameof(ProcessSelectedFolderTooltip));
        OnPropertyChanged(nameof(Professional));
        OnPropertyChanged(nameof(Rating));
        OnPropertyChanged(nameof(RefreshingFolder));
        OnPropertyChanged(nameof(RemoveFromContextMenu));
        OnPropertyChanged(nameof(ResetDefaultPoster));
        OnPropertyChanged(nameof(RestartAsAdmin));
        OnPropertyChanged(nameof(RestartExplorer));
        OnPropertyChanged(nameof(RestartExplorerConfirmation));
        OnPropertyChanged(nameof(RestartExplorerTooltip));
        OnPropertyChanged(nameof(Russian));
        OnPropertyChanged(nameof(Save));
        OnPropertyChanged(nameof(SearchMode));
        OnPropertyChanged(nameof(SearchResult));
        OnPropertyChanged(nameof(Searching));
        OnPropertyChanged(nameof(SearchingWithCount));
        OnPropertyChanged(nameof(SearchingWithName));
        OnPropertyChanged(nameof(SeeMorePosters));
        OnPropertyChanged(nameof(SelectFolder));
        OnPropertyChanged(nameof(SelectIconsDirectory));
        OnPropertyChanged(nameof(SelectPosterIconOverlay));
        OnPropertyChanged(nameof(Settings));
        OnPropertyChanged(nameof(ShowMore));
        OnPropertyChanged(nameof(ShowPosterWindowTooltip));
        OnPropertyChanged(nameof(ShowRatingBadge));
        OnPropertyChanged(nameof(ShowRatingBadgeTooltip));
        OnPropertyChanged(nameof(Skip));
        OnPropertyChanged(nameof(SkipThisPlaceholder));
        OnPropertyChanged(nameof(SkipThisTitle));
        OnPropertyChanged(nameof(Spanish));
        OnPropertyChanged(nameof(StopSearching));
        OnPropertyChanged(nameof(SubfolderProcessing));
        OnPropertyChanged(nameof(TMDBAPIKey));
        OnPropertyChanged(nameof(TV));
        OnPropertyChanged(nameof(Test));
        OnPropertyChanged(nameof(Theme));
        OnPropertyChanged(nameof(ThemeDark));
        OnPropertyChanged(nameof(ThemeLight));
        OnPropertyChanged(nameof(ThemeSystem));
        OnPropertyChanged(nameof(ThisIsLatestVersion));
        OnPropertyChanged(nameof(Title));
        OnPropertyChanged(nameof(ToForceReload));
        OnPropertyChanged(nameof(UnauthorizedAccess));
        OnPropertyChanged(nameof(Undo));
        OnPropertyChanged(nameof(UndoSuccessful));
        OnPropertyChanged(nameof(UpdateNow));
        OnPropertyChanged(nameof(UsePosterOverlay));
        OnPropertyChanged(nameof(Version));
        OnPropertyChanged(nameof(VideoUnavailable));
        OnPropertyChanged(nameof(WebView2DownloadConfirmation));
        OnPropertyChanged(nameof(WebView2DownloadConfirmationHeader));
        OnPropertyChanged(nameof(WritePermissionAllowed));
        OnPropertyChanged(nameof(WritePermissionNotAllowed));
        OnPropertyChanged(nameof(Year));
        OnPropertyChanged(nameof(OnboardingTitle));
        OnPropertyChanged(nameof(OnboardingWelcome));
        OnPropertyChanged(nameof(OnboardingGetStarted));
        OnPropertyChanged(nameof(OnboardingTmdbStep));
        OnPropertyChanged(nameof(OnboardingTmdbInstructions));
        OnPropertyChanged(nameof(OnboardingTmdbGetKey));
        OnPropertyChanged(nameof(OnboardingIgdbStep));
        OnPropertyChanged(nameof(OnboardingIgdbInstructions));
        OnPropertyChanged(nameof(OnboardingIgdbGetKey));
        OnPropertyChanged(nameof(OnboardingDeviantArtStep));
        OnPropertyChanged(nameof(OnboardingDeviantArtAuthInstructions));
        OnPropertyChanged(nameof(OnboardingDeviantArtBuiltIn));
        OnPropertyChanged(nameof(OnboardingDeviantArtCustom));
        OnPropertyChanged(nameof(OnboardingDeviantArtCustomInstructions));
        OnPropertyChanged(nameof(OnboardingDeviantArtValidateConnect));
        OnPropertyChanged(nameof(OnboardingConnectDeviantArt));
        OnPropertyChanged(nameof(OnboardingDeviantArtConnected));
        OnPropertyChanged(nameof(OnboardingDeviantArtNotConnected));
        OnPropertyChanged(nameof(OnboardingDeviantArtConnecting));
        OnPropertyChanged(nameof(OnboardingDeviantArtConnectFailed));
        OnPropertyChanged(nameof(OnboardingValidate));
        OnPropertyChanged(nameof(OnboardingSkip));
        OnPropertyChanged(nameof(OnboardingNext));
        OnPropertyChanged(nameof(OnboardingBack));
        OnPropertyChanged(nameof(OnboardingFinish));
        OnPropertyChanged(nameof(OnboardingValidationSuccess));
        OnPropertyChanged(nameof(OnboardingValidationFailed));
        OnPropertyChanged(nameof(OnboardingNetworkError));
        OnPropertyChanged(nameof(OnboardingValidating));
        OnPropertyChanged(nameof(OnboardingSummary));
        OnPropertyChanged(nameof(OnboardingConfigured));
        OnPropertyChanged(nameof(OnboardingSkipped));
        OnPropertyChanged(nameof(ServiceNotConfigured));
        OnPropertyChanged(nameof(SetupWizard));
        OnPropertyChanged(nameof(AllApiKeysFree));
        OnPropertyChanged(nameof(Notification));
        OnPropertyChanged(nameof(ApiKeyCannotBeEmpty));
        OnPropertyChanged(nameof(ClientIdAndSecretCannotBeEmpty));
        OnPropertyChanged(nameof(ImageFilesFilter));
        OnPropertyChanged(nameof(MadeWithFoliCon));
        OnPropertyChanged(nameof(InvalidApiKey));
        OnPropertyChanged(nameof(InvalidClientIdOrSecret));
        OnPropertyChanged(nameof(RequestTimedOut));
        OnPropertyChanged(nameof(CouldNotReachService));
        OnPropertyChanged(nameof(UnexpectedError));
        OnPropertyChanged(nameof(DeviantArtNoTokens));
        OnPropertyChanged(nameof(DeviantArtClientSecretMissing));
        OnPropertyChanged(nameof(DeviantArtNoRefreshToken));
        OnPropertyChanged(nameof(DeviantArtAccessExpired));
        OnPropertyChanged(nameof(DeviantArtConnectionFailed));
        OnPropertyChanged(nameof(DeviantArtAuthFailed));
        OnPropertyChanged(nameof(DeviantArtMissingCode));
        OnPropertyChanged(nameof(DeviantArtAuthTimedOut));
        OnPropertyChanged(nameof(DeviantArtTokenObtainFailed));
        OnPropertyChanged(nameof(DeviantArtTokenRefreshFailed));
        OnPropertyChanged(nameof(DeviantArtClientCredentialsFailed));
        OnPropertyChanged(nameof(DeviantArtClientAuthFailed));
        OnPropertyChanged(nameof(WatcherWallBadge));
        OnPropertyChanged(nameof(WatcherWallConfirmTitle));
        OnPropertyChanged(nameof(WatcherWallConfirmMessage));
        OnPropertyChanged(nameof(WatcherWallWatchFailedTitle));
        OnPropertyChanged(nameof(WatcherWallWatchFailedMessage));
        OnPropertyChanged(nameof(WatcherWallWatchSuccess));
        OnPropertyChanged(nameof(WatchingArtist));
        OnPropertyChanged(nameof(DeviantArtWatchScopeLabel));
        OnPropertyChanged(nameof(DeviantArtWatchScopeDescription));
        OnPropertyChanged(nameof(DeviantArtWatchScopeReauthNeeded));
        OnPropertyChanged(nameof(DeviantArtWatchScopeNotEnabled));
    }

    public string APIKeysConfiguration => Lang.APIKeysConfiguration;
    public string APIKeysNotProvided => Lang.APIKeysNotProvided;
    public string About => Lang.About;
    public string Action => Lang.Action;
    public string AddToContextMenu => Lang.AddToContextMenu;
    public string All => Lang.All;
    public string AlwaysShowPosterWindow => Lang.AlwaysShowPosterWindow;
    public string AmbiguousTitleTooltip => Lang.AmbiguousTitleTooltip;
    public string AppWillClose => Lang.AppWillClose;
    public string Apply => Lang.Apply;
    public string Arabic => Lang.Arabic;
    public string Auto => Lang.Auto;
    public string BestSuitedForHorizontal => Lang.BestSuitedForHorizontal;
    public string BrowseFolderDropHere => Lang.BrowseFolderDropHere;
    public string BrowseIconsDropHere => Lang.BrowseIconsDropHere;
    public string Cancel => Lang.Cancel;
    public string ChangeLanguage => Lang.ChangeLanguage;
    public string ChangePosterOverlay => Lang.ChangePosterOverlay;
    public string CheckForUpdate => Lang.CheckForUpdate;
    public string ChooseAnImage => Lang.ChooseAnImage;
    public string ChoosePoster => Lang.ChoosePoster;
    public string ClientID => Lang.ClientID;
    public string ClientSecret => Lang.ClientSecret;
    public string Close => Lang.Close;
    public string ClosingApplication => Lang.ClosingApplication;
    public string Configuration => Lang.Configuration;
    public string Confirm => Lang.Confirm;
    public string ConfirmExplorerRestart => Lang.ConfirmExplorerRestart;
    public string ConfirmIconDeletion => Lang.ConfirmIconDeletion;
    public string ConfirmMediaInfoDeletion => Lang.ConfirmMediaInfoDeletion;
    public string ConfirmToOpenFolder => Lang.ConfirmToOpenFolder;
    public string CreatingIconWithCount => Lang.CreatingIconWithCount;
    public string CreatingIcons => Lang.CreatingIcons;
    public string CustomIconSetter => Lang.CustomIconSetter;
    public string CustomRating => Lang.CustomRating;
    public string CustomRatingTooltip => Lang.CustomRatingTooltip;
    public string DeleteIcons => Lang.DeleteIcons;
    public string DeleteIconsConfirmation => Lang.DeleteIconsConfirmation;
    public string DeleteIconsTooltip => Lang.DeleteIconsTooltip;
    public string DeleteMediaInfo => Lang.DeleteMediaInfo;
    public string DeleteMediaInfoConfirmation => Lang.DeleteMediaInfoConfirmation;
    public string DeleteMediaInfoTooltip => Lang.DeleteMediaInfoTooltip;
    public string DevelopedByDinesh => Lang.DevelopedByDinesh;
    public string DirectoryIsEmpty => Lang.DirectoryIsEmpty;
    public string DownloadIt => Lang.DownloadIt;
    public string Downloading => Lang.Downloading;
    public string DownloadingIconWithCount => Lang.DownloadingIconWithCount;
    public string DownloadingIcons => Lang.DownloadingIcons;
    public string EmptyDirectory => Lang.EmptyDirectory;
    public string EnableErrorReporting => Lang.EnableErrorReporting;
    public string EnableErrorReportingTip => Lang.EnableErrorReportingTip;
    public string EnableSubfolderProcessing => Lang.EnableSubfolderProcessing;
    public string IncludeAlreadyProcessed => Lang.IncludeAlreadyProcessed;
    public string IncludeAlreadyProcessedTooltip => Lang.IncludeAlreadyProcessedTooltip;
    public string ProcessSelectedFolder => Lang.ProcessSelectedFolder;
    public string ProcessSelectedFolderTooltip => Lang.ProcessSelectedFolderTooltip;
    public string MaxDepth => Lang.MaxDepth;
    public string MaxDepthTooltip => Lang.MaxDepthTooltip;
    public string Enabled => Lang.Enabled;
    public string English => Lang.English;
    public string EnterTitlePlaceholder => Lang.EnterTitlePlaceholder;
    public string EnterValidRegexPlaceholder => Lang.EnterValidRegexPlaceholder;
    public string ExceptionOccurred => Lang.ExceptionOccurred;
    public string ExplorerIntegration => Lang.ExplorerIntegration;
    public string ExtractGallery => Lang.ExtractGallery;
    public string Extracting => Lang.Extracting;
    public string FailedFileAccessAt => Lang.FailedFileAccessAt;
    public string FailedToSaveMediaInfoAt => Lang.FailedToSaveMediaInfoAt;
    public string FileIsInUse => Lang.FileIsInUse;
    public string Folder => Lang.Folder;
    public string FolderDoesNotExist => Lang.FolderDoesNotExist;
    public string FolderError => Lang.FolderError;
    public string Folders => Lang.Folders;
    public string FoldersProcessed => Lang.FoldersProcessed;
    public string FoliConDescription => Lang.FoliConDescription;
    public string Game => Lang.Game;
    public string HaveIcons => Lang.HaveIcons;
    public string HaveIconsTooltip => Lang.HaveIconsTooltip;
    public string Help => Lang.Help;
    public string HelpDocument => Lang.HelpDocument;
    public string Hindi => Lang.Hindi;
    public string IconCreated => Lang.IconCreated;
    public string IconCreatedWithCount => Lang.IconCreatedWithCount;
    public string IconMode => Lang.IconMode;
    public string IconReloadMayTakeTime => Lang.IconReloadMayTakeTime;
    public string Icons => Lang.Icons;
    public string IconsAlready => Lang.IconsAlready;
    public string IconsCreated => Lang.IconsCreated;
    public string Idle => Lang.Idle;
    public string Ignore => Lang.Ignore;
    public string IgnoreAmbiguousTitle => Lang.IgnoreAmbiguousTitle;
    public string InvalidPath => Lang.InvalidPath;
    public string InvalidRegex => Lang.InvalidRegex;
    public string InvalidRegexMessage => Lang.InvalidRegexMessage;
    public string License => Lang.License;
    public string LicenseInfo => Lang.LicenseInfo;
    public string Load => Lang.Load;
    public string LoadingPosters => Lang.LoadingPosters;
    public string MakeIcons => Lang.MakeIcons;
    public string ManualExplorer => Lang.ManualExplorer;
    public string MediaRating => Lang.MediaRating;
    public string MediaTitle => Lang.MediaTitle;
    public string Movie => Lang.Movie;
    public string NetworkError => Lang.NetworkError;
    public string NetworkNotAvailable => Lang.NetworkNotAvailable;
    public string NewVersionFound => Lang.NewVersionFound;
    public string NoFolderOrIconAlready => Lang.NoFolderOrIconAlready;
    public string NoFoldersToProcess => Lang.NoFoldersToProcess;
    public string NoIconsSelected => Lang.NoIconsSelected;
    public string NoIconsToApply => Lang.NoIconsToApply;
    public string NoInternet => Lang.NoInternet;
    public string NoPosterFound => Lang.NoPosterFound;
    public string NoResult => Lang.NoResult;
    public string NoResultFound => Lang.NoResultFound;
    public string NoResultFoundTryCorrectTitle => Lang.NoResultFoundTryCorrectTitle;
    public string NothingFoundFor => Lang.NothingFoundFor;
    public string OK => Lang.OK;
    public string OnlyKeepExactMatches => Lang.OnlyKeepExactMatches;
    public string Or => Lang.Or;
    public string OutOf => Lang.OutOf;
    public string Overlay => Lang.Overlay;
    public string Pattern => Lang.Pattern;
    public string Patterns => Lang.Patterns;
    public string PickIconWithName => Lang.PickIconWithName;
    public string PickSelected => Lang.PickSelected;
    public string Poster => Lang.Poster;
    public string PosterIconOverlay => Lang.PosterIconOverlay;
    public string PosterOverlayTooltip => Lang.PosterOverlayTooltip;
    public string Previewer => Lang.Previewer;
    public string Professional => Lang.Professional;
    public string Rating => Lang.Rating;
    public string RefreshingFolder => Lang.RefreshingFolder;
    public string RemoveFromContextMenu => Lang.RemoveFromContextMenu;
    public string ResetDefaultPoster => Lang.ResetDefaultPoster;
    public string RestartAsAdmin => Lang.RestartAsAdmin;
    public string RestartExplorer => Lang.RestartExplorer;
    public string RestartExplorerConfirmation => Lang.RestartExplorerConfirmation;
    public string RestartExplorerTooltip => Lang.RestartExplorerTooltip;
    public string Russian => Lang.Russian;
    public string Save => Lang.Save;
    public string SearchMode => Lang.SearchMode;
    public string SearchResult => Lang.SearchResult;
    public string Searching => Lang.Searching;
    public string SearchingWithCount => Lang.SearchingWithCount;
    public string SearchingWithName => Lang.SearchingWithName;
    public string SeeMorePosters => Lang.SeeMorePosters;
    public string SelectFolder => Lang.SelectFolder;
    public string SelectIconsDirectory => Lang.SelectIconsDirectory;
    public string SelectPosterIconOverlay => Lang.SelectPosterIconOverlay;
    public string Settings => Lang.Settings;
    public string ShowMore => Lang.ShowMore;
    public string ShowPosterWindowTooltip => Lang.ShowPosterWindowTooltip;
    public string ShowRatingBadge => Lang.ShowRatingBadge;
    public string ShowRatingBadgeTooltip => Lang.ShowRatingBadgeTooltip;
    public string Skip => Lang.Skip;
    public string SkipThisPlaceholder => Lang.SkipThisPlaceholder;
    public string SkipThisTitle => Lang.SkipThisTitle;
    public string Spanish => Lang.Spanish;
    public string StopSearching => Lang.StopSearching;
    public string SubfolderProcessing => Lang.SubfolderProcessing;
    public string TMDBAPIKey => Lang.TMDBAPIKey;
    public string TV => Lang.TV;
    public string Test => Lang.Test;
    public string Theme => Lang.Theme;
    public string ThemeDark => Lang.ThemeDark;
    public string ThemeLight => Lang.ThemeLight;
    public string ThemeSystem => Lang.ThemeSystem;
    public string ThisIsLatestVersion => Lang.ThisIsLatestVersion;
    public string Title => Lang.Title;
    public string ToForceReload => Lang.ToForceReload;
    public string UnauthorizedAccess => Lang.UnauthorizedAccess;
    public string Undo => Lang.Undo;
    public string UndoSuccessful => Lang.UndoSuccessful;
    public string UpdateNow => Lang.UpdateNow;
    public string UsePosterOverlay => Lang.UsePosterOverlay;
    public string Version => Lang.Version;
    public string VideoUnavailable => Lang.VideoUnavailable;
    public string WebView2DownloadConfirmation => Lang.WebView2DownloadConfirmation;
    public string WebView2DownloadConfirmationHeader => Lang.WebView2DownloadConfirmationHeader;
    public string WritePermissionAllowed => Lang.WritePermissionAllowed;
    public string WritePermissionNotAllowed => Lang.WritePermissionNotAllowed;
    public string Year => Lang.Year;
    public string OnboardingTitle => Lang.OnboardingTitle;
    public string OnboardingWelcome => Lang.OnboardingWelcome;
    public string OnboardingGetStarted => Lang.OnboardingGetStarted;
    public string OnboardingTmdbStep => Lang.OnboardingTmdbStep;
    public string OnboardingTmdbInstructions => Lang.OnboardingTmdbInstructions;
    public string OnboardingTmdbGetKey => Lang.OnboardingTmdbGetKey;
    public string OnboardingIgdbStep => Lang.OnboardingIgdbStep;
    public string OnboardingIgdbInstructions => Lang.OnboardingIgdbInstructions;
    public string OnboardingIgdbGetKey => Lang.OnboardingIgdbGetKey;
    public string OnboardingDeviantArtStep => Lang.OnboardingDeviantArtStep;
    public string OnboardingDeviantArtAuthInstructions => Lang.OnboardingDeviantArtAuthInstructions;
    public string OnboardingDeviantArtBuiltIn => Lang.OnboardingDeviantArtBuiltIn;
    public string OnboardingDeviantArtCustom => Lang.OnboardingDeviantArtCustom;
    public string OnboardingDeviantArtCustomInstructions => Lang.OnboardingDeviantArtCustomInstructions;
    public string OnboardingDeviantArtValidateConnect => Lang.OnboardingDeviantArtValidateConnect;
    public string OnboardingConnectDeviantArt => Lang.OnboardingConnectDeviantArt;
    public string OnboardingDeviantArtConnected => Lang.OnboardingDeviantArtConnected;
    public string OnboardingDeviantArtNotConnected => Lang.OnboardingDeviantArtNotConnected;
    public string OnboardingDeviantArtConnecting => Lang.OnboardingDeviantArtConnecting;
    public string OnboardingDeviantArtConnectFailed => Lang.OnboardingDeviantArtConnectFailed;
    public string OnboardingValidate => Lang.OnboardingValidate;
    public string OnboardingSkip => Lang.OnboardingSkip;
    public string OnboardingNext => Lang.OnboardingNext;
    public string OnboardingBack => Lang.OnboardingBack;
    public string OnboardingFinish => Lang.OnboardingFinish;
    public string OnboardingValidationSuccess => Lang.OnboardingValidationSuccess;
    public string OnboardingValidationFailed => Lang.OnboardingValidationFailed;
    public string OnboardingNetworkError => Lang.OnboardingNetworkError;
    public string OnboardingValidating => Lang.OnboardingValidating;
    public string OnboardingSummary => Lang.OnboardingSummary;
    public string OnboardingConfigured => Lang.OnboardingConfigured;
    public string OnboardingSkipped => Lang.OnboardingSkipped;
    public string ServiceNotConfigured => Lang.ServiceNotConfigured;
    public string SetupWizard => Lang.SetupWizard;
    public string AllApiKeysFree => Lang.AllApiKeysFree;
    public string Notification => Lang.Notification;
    public string ApiKeyCannotBeEmpty => Lang.ApiKeyCannotBeEmpty;
    public string ClientIdAndSecretCannotBeEmpty => Lang.ClientIdAndSecretCannotBeEmpty;
    public string ImageFilesFilter => Lang.ImageFilesFilter;
    public string MadeWithFoliCon => Lang.MadeWithFoliCon;
    public string InvalidApiKey => Lang.InvalidApiKey;
    public string InvalidClientIdOrSecret => Lang.InvalidClientIdOrSecret;
    public string RequestTimedOut => Lang.RequestTimedOut;
    public string CouldNotReachService => Lang.CouldNotReachService;
    public string UnexpectedError => Lang.UnexpectedError;
    public string DeviantArtNoTokens => Lang.DeviantArtNoTokens;
    public string DeviantArtClientSecretMissing => Lang.DeviantArtClientSecretMissing;
    public string DeviantArtNoRefreshToken => Lang.DeviantArtNoRefreshToken;
    public string DeviantArtAccessExpired => Lang.DeviantArtAccessExpired;
    public string DeviantArtConnectionFailed => Lang.DeviantArtConnectionFailed;
    public string DeviantArtAuthFailed => Lang.DeviantArtAuthFailed;
    public string DeviantArtMissingCode => Lang.DeviantArtMissingCode;
    public string DeviantArtAuthTimedOut => Lang.DeviantArtAuthTimedOut;
    public string DeviantArtTokenObtainFailed => Lang.DeviantArtTokenObtainFailed;
    public string DeviantArtTokenRefreshFailed => Lang.DeviantArtTokenRefreshFailed;
    public string DeviantArtClientCredentialsFailed => Lang.DeviantArtClientCredentialsFailed;
    public string DeviantArtClientAuthFailed => Lang.DeviantArtClientAuthFailed;
    public string WatcherWallBadge => Lang.WatcherWallBadge;
    public string WatcherWallConfirmTitle => Lang.WatcherWallConfirmTitle;
    public string WatcherWallConfirmMessage => Lang.WatcherWallConfirmMessage;
    public string WatcherWallWatchFailedTitle => Lang.WatcherWallWatchFailedTitle;
    public string WatcherWallWatchFailedMessage => Lang.WatcherWallWatchFailedMessage;
    public string WatcherWallWatchSuccess => Lang.WatcherWallWatchSuccess;
    public string WatchingArtist => Lang.WatchingArtist;
    public string DeviantArtWatchScopeLabel => Lang.DeviantArtWatchScopeLabel;
    public string DeviantArtWatchScopeDescription => Lang.DeviantArtWatchScopeDescription;
    public string DeviantArtWatchScopeReauthNeeded => Lang.DeviantArtWatchScopeReauthNeeded;
    public string DeviantArtWatchScopeNotEnabled => Lang.DeviantArtWatchScopeNotEnabled;


    public event PropertyChangedEventHandler PropertyChanged;

    protected virtual void OnPropertyChanged(string propertyName) =>
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
}

public static class LangKeys
{
    public static readonly string APIKeysConfiguration = nameof(APIKeysConfiguration);
    public static readonly string APIKeysNotProvided = nameof(APIKeysNotProvided);
    public static readonly string About = nameof(About);
    public static readonly string Action = nameof(Action);
    public static readonly string AddToContextMenu = nameof(AddToContextMenu);
    public static readonly string All = nameof(All);
    public static readonly string AlwaysShowPosterWindow = nameof(AlwaysShowPosterWindow);
    public static readonly string AmbiguousTitleTooltip = nameof(AmbiguousTitleTooltip);
    public static readonly string AppWillClose = nameof(AppWillClose);
    public static readonly string Apply = nameof(Apply);
    public static readonly string Arabic = nameof(Arabic);
    public static readonly string Auto = nameof(Auto);
    public static readonly string BestSuitedForHorizontal = nameof(BestSuitedForHorizontal);
    public static readonly string BrowseFolderDropHere = nameof(BrowseFolderDropHere);
    public static readonly string BrowseIconsDropHere = nameof(BrowseIconsDropHere);
    public static readonly string Cancel = nameof(Cancel);
    public static readonly string ChangeLanguage = nameof(ChangeLanguage);
    public static readonly string ChangePosterOverlay = nameof(ChangePosterOverlay);
    public static readonly string CheckForUpdate = nameof(CheckForUpdate);
    public static readonly string ChooseAnImage = nameof(ChooseAnImage);
    public static readonly string ChoosePoster = nameof(ChoosePoster);
    public static readonly string ClientID = nameof(ClientID);
    public static readonly string ClientSecret = nameof(ClientSecret);
    public static readonly string Close = nameof(Close);
    public static readonly string ClosingApplication = nameof(ClosingApplication);
    public static readonly string Configuration = nameof(Configuration);
    public static readonly string Confirm = nameof(Confirm);
    public static readonly string ConfirmExplorerRestart = nameof(ConfirmExplorerRestart);
    public static readonly string ConfirmIconDeletion = nameof(ConfirmIconDeletion);
    public static readonly string ConfirmMediaInfoDeletion = nameof(ConfirmMediaInfoDeletion);
    public static readonly string ConfirmToOpenFolder = nameof(ConfirmToOpenFolder);
    public static readonly string CreatingIconWithCount = nameof(CreatingIconWithCount);
    public static readonly string CreatingIcons = nameof(CreatingIcons);
    public static readonly string CustomIconSetter = nameof(CustomIconSetter);
    public static readonly string CustomRating = nameof(CustomRating);
    public static readonly string CustomRatingTooltip = nameof(CustomRatingTooltip);
    public static readonly string DeleteIcons = nameof(DeleteIcons);
    public static readonly string DeleteIconsConfirmation = nameof(DeleteIconsConfirmation);
    public static readonly string DeleteIconsTooltip = nameof(DeleteIconsTooltip);
    public static readonly string DeleteMediaInfo = nameof(DeleteMediaInfo);
    public static readonly string DeleteMediaInfoConfirmation = nameof(DeleteMediaInfoConfirmation);
    public static readonly string DeleteMediaInfoTooltip = nameof(DeleteMediaInfoTooltip);
    public static readonly string DevelopedByDinesh = nameof(DevelopedByDinesh);
    public static readonly string DirectoryIsEmpty = nameof(DirectoryIsEmpty);
    public static readonly string DownloadIt = nameof(DownloadIt);
    public static readonly string Downloading = nameof(Downloading);
    public static readonly string DownloadingIconWithCount = nameof(DownloadingIconWithCount);
    public static readonly string DownloadingIcons = nameof(DownloadingIcons);
    public static readonly string EmptyDirectory = nameof(EmptyDirectory);
    public static readonly string EnableErrorReporting = nameof(EnableErrorReporting);
    public static readonly string EnableErrorReportingTip = nameof(EnableErrorReportingTip);
    public static readonly string EnableSubfolderProcessing = nameof(EnableSubfolderProcessing);
    public static readonly string Enabled = nameof(Enabled);
    public static readonly string English = nameof(English);
    public static readonly string EnterTitlePlaceholder = nameof(EnterTitlePlaceholder);
    public static readonly string EnterValidRegexPlaceholder = nameof(EnterValidRegexPlaceholder);
    public static readonly string ExceptionOccurred = nameof(ExceptionOccurred);
    public static readonly string ExplorerIntegration = nameof(ExplorerIntegration);
    public static readonly string ExtractGallery = nameof(ExtractGallery);
    public static readonly string Extracting = nameof(Extracting);
    public static readonly string FailedFileAccessAt = nameof(FailedFileAccessAt);
    public static readonly string FailedToSaveMediaInfoAt = nameof(FailedToSaveMediaInfoAt);
    public static readonly string FileIsInUse = nameof(FileIsInUse);
    public static readonly string Folder = nameof(Folder);
    public static readonly string FolderDoesNotExist = nameof(FolderDoesNotExist);
    public static readonly string FolderError = nameof(FolderError);
    public static readonly string Folders = nameof(Folders);
    public static readonly string FoldersProcessed = nameof(FoldersProcessed);
    public static readonly string FoliConDescription = nameof(FoliConDescription);
    public static readonly string Game = nameof(Game);
    public static readonly string HaveIcons = nameof(HaveIcons);
    public static readonly string HaveIconsTooltip = nameof(HaveIconsTooltip);
    public static readonly string Help = nameof(Help);
    public static readonly string HelpDocument = nameof(HelpDocument);
    public static readonly string Hindi = nameof(Hindi);
    public static readonly string IconCreated = nameof(IconCreated);
    public static readonly string IconCreatedWithCount = nameof(IconCreatedWithCount);
    public static readonly string IconMode = nameof(IconMode);
    public static readonly string IconReloadMayTakeTime = nameof(IconReloadMayTakeTime);
    public static readonly string Icons = nameof(Icons);
    public static readonly string IconsAlready = nameof(IconsAlready);
    public static readonly string IconsCreated = nameof(IconsCreated);
    public static readonly string Idle = nameof(Idle);
    public static readonly string Ignore = nameof(Ignore);
    public static readonly string IgnoreAmbiguousTitle = nameof(IgnoreAmbiguousTitle);
    public static readonly string InvalidPath = nameof(InvalidPath);
    public static readonly string InvalidRegex = nameof(InvalidRegex);
    public static readonly string InvalidRegexMessage = nameof(InvalidRegexMessage);
    public static readonly string License = nameof(License);
    public static readonly string LicenseInfo = nameof(LicenseInfo);
    public static readonly string Load = nameof(Load);
    public static readonly string LoadingPosters = nameof(LoadingPosters);
    public static readonly string MakeIcons = nameof(MakeIcons);
    public static readonly string ManualExplorer = nameof(ManualExplorer);
    public static readonly string MediaRating = nameof(MediaRating);
    public static readonly string MediaTitle = nameof(MediaTitle);
    public static readonly string Movie = nameof(Movie);
    public static readonly string NetworkError = nameof(NetworkError);
    public static readonly string NetworkNotAvailable = nameof(NetworkNotAvailable);
    public static readonly string NewVersionFound = nameof(NewVersionFound);
    public static readonly string NoFolderOrIconAlready = nameof(NoFolderOrIconAlready);
    public static readonly string NoFoldersToProcess = nameof(NoFoldersToProcess);
    public static readonly string NoIconsSelected = nameof(NoIconsSelected);
    public static readonly string NoIconsToApply = nameof(NoIconsToApply);
    public static readonly string NoInternet = nameof(NoInternet);
    public static readonly string NoPosterFound = nameof(NoPosterFound);
    public static readonly string NoResult = nameof(NoResult);
    public static readonly string NoResultFound = nameof(NoResultFound);
    public static readonly string NoResultFoundTryCorrectTitle = nameof(NoResultFoundTryCorrectTitle);
    public static readonly string NothingFoundFor = nameof(NothingFoundFor);
    public static readonly string OK = nameof(OK);
    public static readonly string OnlyKeepExactMatches = nameof(OnlyKeepExactMatches);
    public static readonly string Or = nameof(Or);
    public static readonly string OutOf = nameof(OutOf);
    public static readonly string Overlay = nameof(Overlay);
    public static readonly string Pattern = nameof(Pattern);
    public static readonly string Patterns = nameof(Patterns);
    public static readonly string PickIconWithName = nameof(PickIconWithName);
    public static readonly string PickSelected = nameof(PickSelected);
    public static readonly string Poster = nameof(Poster);
    public static readonly string PosterIconOverlay = nameof(PosterIconOverlay);
    public static readonly string PosterOverlayTooltip = nameof(PosterOverlayTooltip);
    public static readonly string Previewer = nameof(Previewer);
    public static readonly string Professional = nameof(Professional);
    public static readonly string Rating = nameof(Rating);
    public static readonly string RefreshingFolder = nameof(RefreshingFolder);
    public static readonly string RemoveFromContextMenu = nameof(RemoveFromContextMenu);
    public static readonly string ResetDefaultPoster = nameof(ResetDefaultPoster);
    public static readonly string RestartAsAdmin = nameof(RestartAsAdmin);
    public static readonly string RestartExplorer = nameof(RestartExplorer);
    public static readonly string RestartExplorerConfirmation = nameof(RestartExplorerConfirmation);
    public static readonly string RestartExplorerTooltip = nameof(RestartExplorerTooltip);
    public static readonly string Russian = nameof(Russian);
    public static readonly string Save = nameof(Save);
    public static readonly string SearchMode = nameof(SearchMode);
    public static readonly string SearchResult = nameof(SearchResult);
    public static readonly string Searching = nameof(Searching);
    public static readonly string SearchingWithCount = nameof(SearchingWithCount);
    public static readonly string SearchingWithName = nameof(SearchingWithName);
    public static readonly string SeeMorePosters = nameof(SeeMorePosters);
    public static readonly string SelectFolder = nameof(SelectFolder);
    public static readonly string SelectIconsDirectory = nameof(SelectIconsDirectory);
    public static readonly string SelectPosterIconOverlay = nameof(SelectPosterIconOverlay);
    public static readonly string Settings = nameof(Settings);
    public static readonly string ShowMore = nameof(ShowMore);
    public static readonly string ShowPosterWindowTooltip = nameof(ShowPosterWindowTooltip);
    public static readonly string ShowRatingBadge = nameof(ShowRatingBadge);
    public static readonly string ShowRatingBadgeTooltip = nameof(ShowRatingBadgeTooltip);
    public static readonly string Skip = nameof(Skip);
    public static readonly string SkipThisPlaceholder = nameof(SkipThisPlaceholder);
    public static readonly string SkipThisTitle = nameof(SkipThisTitle);
    public static readonly string Spanish = nameof(Spanish);
    public static readonly string StopSearching = nameof(StopSearching);
    public static readonly string SubfolderProcessing = nameof(SubfolderProcessing);
    public static readonly string TMDBAPIKey = nameof(TMDBAPIKey);
    public static readonly string TV = nameof(TV);
    public static readonly string Test = nameof(Test);
    public static readonly string Theme = nameof(Theme);
    public static readonly string ThemeDark = nameof(ThemeDark);
    public static readonly string ThemeLight = nameof(ThemeLight);
    public static readonly string ThemeSystem = nameof(ThemeSystem);
    public static readonly string ThisIsLatestVersion = nameof(ThisIsLatestVersion);
    public static readonly string Title = nameof(Title);
    public static readonly string ToForceReload = nameof(ToForceReload);
    public static readonly string UnauthorizedAccess = nameof(UnauthorizedAccess);
    public static readonly string Undo = nameof(Undo);
    public static readonly string UndoSuccessful = nameof(UndoSuccessful);
    public static readonly string UpdateNow = nameof(UpdateNow);
    public static readonly string UsePosterOverlay = nameof(UsePosterOverlay);
    public static readonly string Version = nameof(Version);
    public static readonly string VideoUnavailable = nameof(VideoUnavailable);
    public static readonly string WebView2DownloadConfirmation = nameof(WebView2DownloadConfirmation);
    public static readonly string WebView2DownloadConfirmationHeader = nameof(WebView2DownloadConfirmationHeader);
    public static readonly string WritePermissionAllowed = nameof(WritePermissionAllowed);
    public static readonly string WritePermissionNotAllowed = nameof(WritePermissionNotAllowed);
    public static readonly string Year = nameof(Year);

    public static readonly string OnboardingTitle = nameof(OnboardingTitle);
    public static readonly string OnboardingWelcome = nameof(OnboardingWelcome);
    public static readonly string OnboardingGetStarted = nameof(OnboardingGetStarted);
    public static readonly string OnboardingTmdbStep = nameof(OnboardingTmdbStep);
    public static readonly string OnboardingTmdbInstructions = nameof(OnboardingTmdbInstructions);
    public static readonly string OnboardingTmdbGetKey = nameof(OnboardingTmdbGetKey);
    public static readonly string OnboardingIgdbStep = nameof(OnboardingIgdbStep);
    public static readonly string OnboardingIgdbInstructions = nameof(OnboardingIgdbInstructions);
    public static readonly string OnboardingIgdbGetKey = nameof(OnboardingIgdbGetKey);
    public static readonly string OnboardingDeviantArtStep = nameof(OnboardingDeviantArtStep);
    public static readonly string OnboardingDeviantArtAuthInstructions = nameof(OnboardingDeviantArtAuthInstructions);
    public static readonly string OnboardingDeviantArtBuiltIn = nameof(OnboardingDeviantArtBuiltIn);
    public static readonly string OnboardingDeviantArtCustom = nameof(OnboardingDeviantArtCustom);
    public static readonly string OnboardingDeviantArtCustomInstructions =
        nameof(OnboardingDeviantArtCustomInstructions);
    public static readonly string OnboardingDeviantArtValidateConnect = nameof(OnboardingDeviantArtValidateConnect);
    public static readonly string OnboardingConnectDeviantArt = nameof(OnboardingConnectDeviantArt);
    public static readonly string OnboardingDeviantArtConnected = nameof(OnboardingDeviantArtConnected);
    public static readonly string OnboardingDeviantArtNotConnected = nameof(OnboardingDeviantArtNotConnected);
    public static readonly string OnboardingDeviantArtConnecting = nameof(OnboardingDeviantArtConnecting);
    public static readonly string OnboardingDeviantArtConnectFailed = nameof(OnboardingDeviantArtConnectFailed);
    public static readonly string OnboardingValidate = nameof(OnboardingValidate);
    public static readonly string OnboardingSkip = nameof(OnboardingSkip);
    public static readonly string OnboardingNext = nameof(OnboardingNext);
    public static readonly string OnboardingBack = nameof(OnboardingBack);
    public static readonly string OnboardingFinish = nameof(OnboardingFinish);
    public static readonly string OnboardingValidationSuccess = nameof(OnboardingValidationSuccess);
    public static readonly string OnboardingValidationFailed = nameof(OnboardingValidationFailed);
    public static readonly string OnboardingNetworkError = nameof(OnboardingNetworkError);
    public static readonly string OnboardingValidating = nameof(OnboardingValidating);
    public static readonly string OnboardingSummary = nameof(OnboardingSummary);
    public static readonly string OnboardingConfigured = nameof(OnboardingConfigured);
    public static readonly string OnboardingSkipped = nameof(OnboardingSkipped);
    public static readonly string ServiceNotConfigured = nameof(ServiceNotConfigured);
    public static readonly string SetupWizard = nameof(SetupWizard);
    public static readonly string AllApiKeysFree = nameof(AllApiKeysFree);
    public static readonly string Notification = nameof(Notification);
    public static readonly string ApiKeyCannotBeEmpty = nameof(ApiKeyCannotBeEmpty);
    public static readonly string ClientIdAndSecretCannotBeEmpty = nameof(ClientIdAndSecretCannotBeEmpty);
    public static readonly string ImageFilesFilter = nameof(ImageFilesFilter);
    public static readonly string MadeWithFoliCon = nameof(MadeWithFoliCon);
    public static readonly string InvalidApiKey = nameof(InvalidApiKey);
    public static readonly string InvalidClientIdOrSecret = nameof(InvalidClientIdOrSecret);
    public static readonly string RequestTimedOut = nameof(RequestTimedOut);
    public static readonly string CouldNotReachService = nameof(CouldNotReachService);
    public static readonly string UnexpectedError = nameof(UnexpectedError);
    public static readonly string DeviantArtNoTokens = nameof(DeviantArtNoTokens);
    public static readonly string DeviantArtClientSecretMissing = nameof(DeviantArtClientSecretMissing);
    public static readonly string DeviantArtNoRefreshToken = nameof(DeviantArtNoRefreshToken);
    public static readonly string DeviantArtAccessExpired = nameof(DeviantArtAccessExpired);
    public static readonly string DeviantArtConnectionFailed = nameof(DeviantArtConnectionFailed);
    public static readonly string DeviantArtAuthFailed = nameof(DeviantArtAuthFailed);
    public static readonly string DeviantArtMissingCode = nameof(DeviantArtMissingCode);
    public static readonly string DeviantArtAuthTimedOut = nameof(DeviantArtAuthTimedOut);
    public static readonly string DeviantArtTokenObtainFailed = nameof(DeviantArtTokenObtainFailed);
    public static readonly string DeviantArtTokenRefreshFailed = nameof(DeviantArtTokenRefreshFailed);
    public static readonly string DeviantArtClientCredentialsFailed = nameof(DeviantArtClientCredentialsFailed);
    public static readonly string DeviantArtClientAuthFailed = nameof(DeviantArtClientAuthFailed);
    public static readonly string WatcherWallBadge = nameof(WatcherWallBadge);
    public static readonly string WatcherWallConfirmTitle = nameof(WatcherWallConfirmTitle);
    public static readonly string WatcherWallConfirmMessage = nameof(WatcherWallConfirmMessage);
    public static readonly string WatcherWallWatchFailedTitle = nameof(WatcherWallWatchFailedTitle);
    public static readonly string WatcherWallWatchFailedMessage = nameof(WatcherWallWatchFailedMessage);
    public static readonly string WatcherWallWatchSuccess = nameof(WatcherWallWatchSuccess);
    public static readonly string WatchingArtist = nameof(WatchingArtist);
    public static readonly string DeviantArtWatchScopeLabel = nameof(DeviantArtWatchScopeLabel);
    public static readonly string DeviantArtWatchScopeDescription = nameof(DeviantArtWatchScopeDescription);
    public static readonly string DeviantArtWatchScopeReauthNeeded = nameof(DeviantArtWatchScopeReauthNeeded);
    public static readonly string DeviantArtWatchScopeNotEnabled = nameof(DeviantArtWatchScopeNotEnabled);
    public static readonly string IncludeAlreadyProcessed = nameof(IncludeAlreadyProcessed);
    public static readonly string IncludeAlreadyProcessedTooltip = nameof(IncludeAlreadyProcessedTooltip);
    public static readonly string ProcessSelectedFolder = nameof(ProcessSelectedFolder);
    public static readonly string ProcessSelectedFolderTooltip = nameof(ProcessSelectedFolderTooltip);
    public static readonly string MaxDepth = nameof(MaxDepth);
    public static readonly string MaxDepthTooltip = nameof(MaxDepthTooltip);
}
