theme: jekyll-theme-cayman
title: Folicon v3.11
subtitle: The ultimate movie, show, games folder icon customizer
description: Folicon is a Folder icon changer which works for movie,games,music and shows/anime, it also shows rating on the created icons, and has two mode, POSTER and Professional, Professional mode icons are fetched from DeviantArt.
show_downloads: "true"
github:
  zip_url: https://github.com/DineshSolanki/FoliCon/releases/
  tar_url: https://github.com/DineshSolanki/FoliCon/archive/
footer_links:
  linkedin_username: dineshsolanki
