files:
  - source: /FoliCon/Properties/Langs/Lang.resx
    translation: /FoliCon/Properties/Langs/Lang.%two_letters_code%.resx
    update_option: update_as_unapproved

"preserve_hierarchy": true

project_id: 625616
api_token: CROWDIN_API_TOKEN
base_path: .
