"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

"files": [
   {
      "source": "/FoliCon/Properties/Langs/Lang.resx",
      "translation": "/FoliCon/Properties/Langs/Lang.%two_letters_code%.resx",
      "update_option": "update_as_unapproved",
      "languages_mapping": {
         "two_letters_code": {
            "es": "es",
            "pt": "pt",
            "ru": "ru",
            "ar": "ar",
            "hi": "hi"
         }
      }
   }
]