//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoliCon.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoliCon.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show poster window.
        /// </summary>
        public static string AlwaysShowPosterWindow {
            get {
                return ResourceManager.GetString("AlwaysShowPosterWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip ambiguous titles from search.
        /// </summary>
        public static string AmbiguousTitleTooltip {
            get {
                return ResourceManager.GetString("AmbiguousTitleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _API keys Configuration.
        /// </summary>
        public static string APIKeysConfiguration {
            get {
                return ResourceManager.GetString("APIKeysConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (Movies &amp;amp; TV Shows).
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Change Poster Icon overlay.
        /// </summary>
        public static string ChangePosterOverlay {
            get {
                return ResourceManager.GetString("ChangePosterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Icons.
        /// </summary>
        public static string DeleteIcons {
            get {
                return ResourceManager.GetString("DeleteIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete existing icons from all subFolders..
        /// </summary>
        public static string DeleteIconsTooltip {
            get {
                return ResourceManager.GetString("DeleteIconsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Icons.
        /// </summary>
        public static string DownloadingIcons {
            get {
                return ResourceManager.GetString("DownloadingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders Processed:.
        /// </summary>
        public static string FoldersProcessed {
            get {
                return ResourceManager.GetString("FoldersProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you already have icons?.
        /// </summary>
        public static string HaveIcons {
            get {
                return ResourceManager.GetString("HaveIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let you set your own icons(only png and ico allowed)..
        /// </summary>
        public static string HaveIconsTooltip {
            get {
                return ResourceManager.GetString("HaveIconsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Document.
        /// </summary>
        public static string HelpDocument {
            get {
                return ResourceManager.GetString("HelpDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Mode.
        /// </summary>
        public static string IconMode {
            get {
                return ResourceManager.GetString("IconMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons Created :.
        /// </summary>
        public static string IconsCreated {
            get {
                return ResourceManager.GetString("IconsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Ambiguous title.
        /// </summary>
        public static string IgnoreAmbiguousTitle {
            get {
                return ResourceManager.GetString("IgnoreAmbiguousTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string LangComment {
            get {
                return ResourceManager.GetString("LangComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Icons.
        /// </summary>
        public static string MakeIcons {
            get {
                return ResourceManager.GetString("MakeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out of.
        /// </summary>
        public static string OutOf {
            get {
                return ResourceManager.GetString("OutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster.
        /// </summary>
        public static string Poster {
            get {
                return ResourceManager.GetString("Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to use poster Overlay or Plain Posters..
        /// </summary>
        public static string PosterOverlayTooltip {
            get {
                return ResourceManager.GetString("PosterOverlayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        public static string Professional {
            get {
                return ResourceManager.GetString("Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Explorer.
        /// </summary>
        public static string RestartExplorer {
            get {
                return ResourceManager.GetString("RestartExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will close all Open folders and Restart Explorer..
        /// </summary>
        public static string RestartExplorerTooltip {
            get {
                return ResourceManager.GetString("RestartExplorerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mode.
        /// </summary>
        public static string SearchMode {
            get {
                return ResourceManager.GetString("SearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show poster window even if exact title found.this would let you chose different poster for them and custom rating also&amp;#x0a; this overrides &apos;Ignore Ambiguous title&apos; option..
        /// </summary>
        public static string ShowPosterWindowTooltip {
            get {
                return ResourceManager.GetString("ShowPosterWindowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Rating badge.
        /// </summary>
        public static string ShowRatingBadge {
            get {
                return ResourceManager.GetString("ShowRatingBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to hide or show Rating Shield.
        /// </summary>
        public static string ShowRatingBadgeTootip {
            get {
                return ResourceManager.GetString("ShowRatingBadgeTootip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Poster overlay.
        /// </summary>
        public static string UsePosterOverlay {
            get {
                return ResourceManager.GetString("UsePosterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
