//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoliCon.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoliCon.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show poster window.
        /// </summary>
        public static string AlwaysShowPosterWindow {
            get {
                return ResourceManager.GetString("AlwaysShowPosterWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip ambiguous titles from search.
        /// </summary>
        public static string AmbiguousTitleTooltip {
            get {
                return ResourceManager.GetString("AmbiguousTitleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _API keys Configuration.
        /// </summary>
        public static string APIKeysConfiguration {
            get {
                return ResourceManager.GetString("APIKeysConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API keys not provided.
        /// </summary>
        public static string APIKeysNotProvided {
            get {
                return ResourceManager.GetString("APIKeysNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Application will close..
        /// </summary>
        public static string AppWillClose {
            get {
                return ResourceManager.GetString("AppWillClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (Movies &amp; TV Shows).
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Change Poster Icon overlay.
        /// </summary>
        public static string ChangePosterOverlay {
            get {
                return ResourceManager.GetString("ChangePosterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Application.
        /// </summary>
        public static string ClosingApplication {
            get {
                return ResourceManager.GetString("ClosingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Explorer Restart.
        /// </summary>
        public static string ConfirmExplorerRestart {
            get {
                return ResourceManager.GetString("ConfirmExplorerRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Icon Deletion.
        /// </summary>
        public static string ConfirmIconDeletion {
            get {
                return ResourceManager.GetString("ConfirmIconDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Confirm&quot; to open folder..
        /// </summary>
        public static string ConfirmToOpenFolder {
            get {
                return ResourceManager.GetString("ConfirmToOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Icons....
        /// </summary>
        public static string CreatingIcons {
            get {
                return ResourceManager.GetString("CreatingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom rating: .
        /// </summary>
        public static string CustomRating {
            get {
                return ResourceManager.GetString("CustomRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lets you set your own rating instead of one fetched by FoliCon..
        /// </summary>
        public static string CustomRatingTooltip {
            get {
                return ResourceManager.GetString("CustomRatingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Icons.
        /// </summary>
        public static string DeleteIcons {
            get {
                return ResourceManager.GetString("DeleteIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all Icons?.
        /// </summary>
        public static string DeleteIconsConfirmation {
            get {
                return ResourceManager.GetString("DeleteIconsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete existing icons from all subFolders..
        /// </summary>
        public static string DeleteIconsTooltip {
            get {
                return ResourceManager.GetString("DeleteIconsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is Empty.
        /// </summary>
        public static string DirectoryIsEmpty {
            get {
                return ResourceManager.GetString("DirectoryIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Icons.
        /// </summary>
        public static string DownloadingIcons {
            get {
                return ResourceManager.GetString("DownloadingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Icon {0}/{1}....
        /// </summary>
        public static string DownloadingIconWithCount {
            get {
                return ResourceManager.GetString("DownloadingIconWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download it.
        /// </summary>
        public static string DownloadIt {
            get {
                return ResourceManager.GetString("DownloadIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Directory.
        /// </summary>
        public static string EmptyDirectory {
            get {
                return ResourceManager.GetString("EmptyDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Title here to search again..
        /// </summary>
        public static string EnterTitlePlaceholder {
            get {
                return ResourceManager.GetString("EnterTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist!.
        /// </summary>
        public static string FolderDoesNotExist {
            get {
                return ResourceManager.GetString("FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Error.
        /// </summary>
        public static string FolderError {
            get {
                return ResourceManager.GetString("FolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders Processed:.
        /// </summary>
        public static string FoldersProcessed {
            get {
                return ResourceManager.GetString("FoldersProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you already have icons?.
        /// </summary>
        public static string HaveIcons {
            get {
                return ResourceManager.GetString("HaveIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let you set your own icons(only png and ico allowed)..
        /// </summary>
        public static string HaveIconsTooltip {
            get {
                return ResourceManager.GetString("HaveIconsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Document.
        /// </summary>
        public static string HelpDocument {
            get {
                return ResourceManager.GetString("HelpDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon(s) Created.
        /// </summary>
        public static string IconCreated {
            get {
                return ResourceManager.GetString("IconCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Icon created.
        /// </summary>
        public static string IconCreatedWithCount {
            get {
                return ResourceManager.GetString("IconCreatedWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Mode.
        /// </summary>
        public static string IconMode {
            get {
                return ResourceManager.GetString("IconMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:The Icon may take some time to reload..
        /// </summary>
        public static string IconReloadMayTakeTime {
            get {
                return ResourceManager.GetString("IconReloadMayTakeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder already have Icons or is Empty!.
        /// </summary>
        public static string IconsAlready {
            get {
                return ResourceManager.GetString("IconsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons Created :.
        /// </summary>
        public static string IconsCreated {
            get {
                return ResourceManager.GetString("IconsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Ambiguous title.
        /// </summary>
        public static string IgnoreAmbiguousTitle {
            get {
                return ResourceManager.GetString("IgnoreAmbiguousTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Path.
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading posters....
        /// </summary>
        public static string LoadingPosters {
            get {
                return ResourceManager.GetString("LoadingPosters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Icons.
        /// </summary>
        public static string MakeIcons {
            get {
                return ResourceManager.GetString("MakeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network not available!.
        /// </summary>
        public static string NetworkNotAvailable {
            get {
                return ResourceManager.GetString("NetworkNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version({0}) Found!
        ///Changelog:{1}.
        /// </summary>
        public static string NewVersionFound {
            get {
                return ResourceManager.GetString("NewVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Internet is Not available..
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No poster found..
        /// </summary>
        public static string NoPosterFound {
            get {
                return ResourceManager.GetString("NoPosterFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result.
        /// </summary>
        public static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result Found..
        /// </summary>
        public static string NoResultFound {
            get {
                return ResourceManager.GetString("NoResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result Found, Try to search again with correct title..
        /// </summary>
        public static string NoResultFoundTryCorrectTitle {
            get {
                return ResourceManager.GetString("NoResultFoundTryCorrectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found for {0}
        ///Try Searching with Other Title
        /// or check Search Mode.
        /// </summary>
        public static string NothingFoundFor {
            get {
                return ResourceManager.GetString("NothingFoundFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~ OR ~.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out of.
        /// </summary>
        public static string OutOf {
            get {
                return ResourceManager.GetString("OutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Icon for {0}.
        /// </summary>
        public static string PickIconWithName {
            get {
                return ResourceManager.GetString("PickIconWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Selected.
        /// </summary>
        public static string PickSelected {
            get {
                return ResourceManager.GetString("PickSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster.
        /// </summary>
        public static string Poster {
            get {
                return ResourceManager.GetString("Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to use poster Overlay or Plain Posters..
        /// </summary>
        public static string PosterOverlayTooltip {
            get {
                return ResourceManager.GetString("PosterOverlayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        public static string Professional {
            get {
                return ResourceManager.GetString("Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Explorer.
        /// </summary>
        public static string RestartExplorer {
            get {
                return ResourceManager.GetString("RestartExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Restart Explorer 
        ///and refresh Icon Cache?.
        /// </summary>
        public static string RestartExplorerConfirmation {
            get {
                return ResourceManager.GetString("RestartExplorerConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will close all Open folders and Restart Explorer..
        /// </summary>
        public static string RestartExplorerTooltip {
            get {
                return ResourceManager.GetString("RestartExplorerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching...{0}.
        /// </summary>
        public static string SearchingWithCount {
            get {
                return ResourceManager.GetString("SearchingWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for {0}....
        /// </summary>
        public static string SearchingWithName {
            get {
                return ResourceManager.GetString("SearchingWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mode.
        /// </summary>
        public static string SearchMode {
            get {
                return ResourceManager.GetString("SearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more posters/covers..
        /// </summary>
        public static string SeeMorePosters {
            get {
                return ResourceManager.GetString("SeeMorePosters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more....
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show poster window even if exact title found.this would let you chose different poster for them and custom rating also &amp;#x0a; this overrides &apos;Ignore Ambiguous title&apos; option..
        /// </summary>
        public static string ShowPosterWindowTooltip {
            get {
                return ResourceManager.GetString("ShowPosterWindowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Rating badge.
        /// </summary>
        public static string ShowRatingBadge {
            get {
                return ResourceManager.GetString("ShowRatingBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to hide or show Rating Shield.
        /// </summary>
        public static string ShowRatingBadgeTooltip {
            get {
                return ResourceManager.GetString("ShowRatingBadgeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this and all remaining titles..
        /// </summary>
        public static string SkipThisPlaceholder {
            get {
                return ResourceManager.GetString("SkipThisPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this title..
        /// </summary>
        public static string SkipThisTitle {
            get {
                return ResourceManager.GetString("SkipThisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Searching.
        /// </summary>
        public static string StopSearching {
            get {
                return ResourceManager.GetString("StopSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! you are using the latest version..
        /// </summary>
        public static string ThisIsLatestVersion {
            get {
                return ResourceManager.GetString("ThisIsLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Force Reload, click on Restart Explorer..
        /// </summary>
        public static string ToForceReload {
            get {
                return ResourceManager.GetString("ToForceReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Now.
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Poster overlay.
        /// </summary>
        public static string UsePosterOverlay {
            get {
                return ResourceManager.GetString("UsePosterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
