using System.Drawing;
using System.IO;
using FoliCon.Models.Data;
using FoliCon.Modules.Overlays;
using FoliCon.Views;
using PosterIcon = FoliCon.Models.Data.PosterIcon;

namespace FoliconTest;

/// <summary>
/// Golden-image pixel parity tests: render each overlay via DynamicPosterIcon
/// and compare against reference PNGs exported from the old compiled XAML views.
///
/// Reference images are generated by running FoliCon once with
/// ReferenceImageExporter.ExportToTestProject() called from App startup.
/// They live in FoliconTest/Resources/ReferenceOverlays/{id}_reference.png.
///
/// DynamicPosterIcon uses explicit pack URIs and works in headless test runners.
/// The reference PNGs capture the old XAML view output from a real app context.
/// </summary>
public sealed class GoldenImageParityTests : IDisposable
{
    private readonly WpfTestHost _host = new();
    private readonly OverlayProvider _provider = new();

    private static readonly string ReferenceDir = Path.Combine(
        FindTestProjectRoot(), "Resources", "ReferenceOverlays");

    private static readonly string[] OverlayIds =
        ["legacy", "alternate", "liaher", "faelpessoal", "faelpessoal-horizontal", "windows11"];

    [Theory]
    [InlineData("legacy")]
    [InlineData("alternate")]
    [InlineData("liaher")]
    [InlineData("faelpessoal")]
    [InlineData("faelpessoal-horizontal")]
    [InlineData("windows11")]
    public void Overlay_DynamicMatchesReference_PixelParity(string overlayId)
    {
        var refPath = Path.Combine(ReferenceDir, $"{overlayId}_reference.png");
        Assert.True(File.Exists(refPath),
            $"Reference image not found: {refPath}. Run FoliCon once with ReferenceImageExporter.ExportToTestProject() to generate it.");

        var definition = _provider.GetOverlayById(overlayId);
        Assert.NotNull(definition);

        var posterIcon = _host.Invoke(() => new PosterIcon());
        try
        {
            // Render via DynamicPosterIcon on STA thread
            using var newBitmap = _host.Invoke(() =>
            {
                var dynamicIcon = new DynamicPosterIcon(definition, posterIcon);
                return dynamicIcon.RenderToBitmap();
            });

            // Load reference image (rendered from old XAML view in the actual app)
            using var refBitmap = new Bitmap(refPath);

            Assert.Equal(refBitmap.Width, newBitmap.Width);
            Assert.Equal(refBitmap.Height, newBitmap.Height);

            // Save rendered and diff images for human review
            var reviewDir = Path.Combine(ReferenceDir, "Review");
            Directory.CreateDirectory(reviewDir);
            newBitmap.Save(Path.Combine(reviewDir, $"{overlayId}_rendered.png"), System.Drawing.Imaging.ImageFormat.Png);
            SaveDiffImage(refBitmap, newBitmap, Path.Combine(reviewDir, $"{overlayId}_diff.png"));

            var (diffCount, maxChannelDiff) = CompareBitmaps(refBitmap, newBitmap);

            // Allow up to 100 pixels with per-channel difference > 10.
            // Sub-pixel antialiasing and image loading path differences
            // (pack URI vs BAML resource loader) account for minor variance.
            // Threshold is intentionally tight to catch real rendering bugs
            // (e.g. wrong layer order, missing clip, incorrect margins).
            Assert.True(diffCount <= 100,
                $"Overlay '{overlayId}': {diffCount} pixels differ by >10 per channel " +
                $"(max channel diff: {maxChannelDiff}). Threshold: 200 pixels.");
        }
        finally
        {
            posterIcon.Dispose();
        }
    }

    [Fact]
    public void AllOverlays_ReferenceImagesExist()
    {
        foreach (var overlayId in OverlayIds)
        {
            var refPath = Path.Combine(ReferenceDir, $"{overlayId}_reference.png");
            Assert.True(File.Exists(refPath),
                $"Reference image missing for '{overlayId}': {refPath}");
        }
    }

    [Fact]
    public void AllOverlays_DynamicPosterIcon_RendersSuccessfully()
    {
        foreach (var overlayId in OverlayIds)
        {
            var definition = _provider.GetOverlayById(overlayId);
            Assert.NotNull(definition);

            var posterIcon = _host.Invoke(() => new PosterIcon());
            try
            {
                using var bitmap = _host.Invoke(() =>
                {
                    var dynamicIcon = new DynamicPosterIcon(definition, posterIcon);
                    return dynamicIcon.RenderToBitmap();
                });

                Assert.NotNull(bitmap);
                Assert.Equal(256, bitmap.Width);
                Assert.Equal(256, bitmap.Height);
            }
            finally
            {
                posterIcon.Dispose();
            }
        }
    }

    /// <summary>
    /// Compare two bitmaps pixel-by-pixel.
    /// Returns (diffCount, maxChannelDiff) where diffCount is the number of pixels
    /// where any channel differs by more than the tolerance.
    /// </summary>
    private static (int diffCount, int maxChannelDiff) CompareBitmaps(Bitmap a, Bitmap b, int tolerance = 10)
    {
        int diffCount = 0;
        int maxChannelDiff = 0;

        for (int y = 0; y < a.Height; y++)
        {
            for (int x = 0; x < a.Width; x++)
            {
                var pa = a.GetPixel(x, y);
                var pb = b.GetPixel(x, y);

                int dr = Math.Abs(pa.R - pb.R);
                int dg = Math.Abs(pa.G - pb.G);
                int db = Math.Abs(pa.B - pb.B);
                int da = Math.Abs(pa.A - pb.A);

                int channelMax = Math.Max(Math.Max(dr, dg), Math.Max(db, da));
                if (channelMax > maxChannelDiff)
                    maxChannelDiff = channelMax;

                if (channelMax > tolerance)
                    diffCount++;
            }
        }

        return (diffCount, maxChannelDiff);
    }

    /// <summary>
    /// Generate a diff image: identical pixels are darkened, differing pixels are
    /// highlighted with amplified channel differences (10x) for visual inspection.
    /// </summary>
    private static void SaveDiffImage(Bitmap reference, Bitmap rendered, string path)
    {
        using var diff = new Bitmap(reference.Width, reference.Height);
        for (int y = 0; y < reference.Height; y++)
        {
            for (int x = 0; x < reference.Width; x++)
            {
                var pr = reference.GetPixel(x, y);
                var pn = rendered.GetPixel(x, y);
                int dr = Math.Abs(pr.R - pn.R);
                int dg = Math.Abs(pr.G - pn.G);
                int db = Math.Abs(pr.B - pn.B);
                int max = Math.Max(Math.Max(dr, dg), db);

                if (max <= 10)
                {
                    // Identical (within tolerance): show as dim grayscale of original
                    int gray = (pr.R + pr.G + pr.B) / 3 / 4; // darken to 25%
                    diff.SetPixel(x, y, Color.FromArgb(255, gray, gray, gray));
                }
                else
                {
                    // Different: highlight with amplified red channel
                    diff.SetPixel(x, y, Color.FromArgb(255,
                        Math.Min(255, dr * 10),
                        Math.Min(255, dg * 5),
                        Math.Min(255, db * 5)));
                }
            }
        }
        diff.Save(path, System.Drawing.Imaging.ImageFormat.Png);
    }

    private static string FindTestProjectRoot()
    {
        // Walk up from the test assembly location to find the FoliconTest directory
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            if (Directory.Exists(Path.Combine(dir.FullName, "Resources", "ReferenceOverlays")))
                return dir.FullName;
            if (dir.Name == "FoliconTest")
                return dir.FullName;
            dir = dir.Parent;
        }
        // Fallback: assume we're in bin/Debug/net10.0-windows10.0.26100.0/
        return Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", ".."));
    }

    public void Dispose()
    {
        _host.Dispose();
    }
}
