name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Welcome to FoliCon! 👋

          Thanks for opening your first issue. A maintainer will review it shortly.

          In the meantime, check out:
          - [Documentation](https://dineshsolanki.github.io/FoliCon-docs/)
          - [Contributing Guide](https://github.com/DineshSolanki/FoliCon/blob/master/CONTRIBUTING.md)

        pr-message: |
          Welcome to FoliCon! 🎉

          Thanks for your first contribution! Here's what to expect:
          - CI will run a build and SonarCloud analysis automatically
          - A maintainer will review your PR once checks pass
          - Please make sure you've filled out the PR template

          Useful resources:
          - [Contributing Guide](https://github.com/DineshSolanki/FoliCon/blob/master/CONTRIBUTING.md)
          - [Documentation](https://dineshsolanki.github.io/FoliCon-docs/)
